<tr>
    <td class="foot" colspan="2">
    <?php
    include "creator.php";
    ?>
	
    </td>
</tr>
</table>
<div class="galery display_none">
<div class="position_fixed galery_back"></div>
   <div class="position_fixed z_index_9999 gall_position photo_gallery galery_floors_shadow back_and_padding_photo_gallery">			  
   				   <div class="top_left_arrow gal_arrow_left position_absolute gal_arrow_height_"><div class="gal_arrow "></div></div>	
   				   <div class="top_right_arrow gal_arrow_right position_absolute gal_arrow_height_"><div class="gal_arrow gal_arrow_right_pos"></div></div>	
   				    <div class="position_relative">
   				    	 <div class="position_absolute">
   				    		<div id="count"></div>
   				    	 </div>
   				    </div>
                     <div class="position_relative overflow_hidden photo_gallery">
		    		    		<div id="for-map"></div>
    		    	     </div>
    		     
   </div>
</div>