<?php $page->addFsize('css/sgal1.css','galsize'); 
      $page->addScript('js/gal.js');
?>
<div class="m-b">
<div class="cl"></div>
    <div class="b-delim-t">
        <div class="f-l">
            <div class="d-bottom-left"></div>
        </div>
        <div class="f-r">
            <div class="d-bottom-right"></div>
        </div>
         <div class="p-r" style="top:12px;">
            <div class="d-bottom-center" ></div>
        </div>
         <div class="p-r" style="top:-1px;margin:0 85px;">
            <div class="d-bottom-l" ></div>
         </div>
     </div>
    <div class="cl"></div>
    <div class="footer-t-ots"></div>
    <div class="footer mar_40">
    <ul style="margin-top:13px;width:100%;">
            <li class="f-l" style="width:32%;">
                <div class="b-text">
                    &copy;&nbsp;<span style="font-family:Times New Roman"><?php echo date('Y');?></span>&nbsp;Усадьба&nbsp;«Люфари»
                    <p><a href="/contacts">Украина,&nbsp;Донецк,&nbsp;ул.&nbsp;Калинина,&nbsp;<span style="font-family:times new roman">118</span></a></p>
                </div>

				<div class="like_block" style="margin-top: 8px;">
				
				<!--img  class="" src="img/like_temp.png"  style="position: absolute;z-index: 100000;width: 257px;height: 20px;" /-->
<!--img  class="like_hover" src="img/like-hov.png"  style="position: absolute;z-index: 10;width: 257px;height: 27px;" /-->

<div class="f-l">
<div id="vk_like"></div>
<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "mini"});
</script>


</div>
<div class="f-l">


<div class="g-plusone" data-size="medium"></div>
<script type="text/javascript">
  window.___gcfg = {lang: 'ru'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script></div>
<div class="f-l"><div id="ok_shareWidget"></div>
<script>
!function (d, id, did, st) {
  var js = d.createElement("script");
  js.src = "http://connect.ok.ru/connect.js";
  js.onload = js.onreadystatechange = function () {
  if (!this.readyState || this.readyState == "loaded" || this.readyState == "complete") {
    if (!this.executed) {
      this.executed = true;
      setTimeout(function () {
        OK.CONNECT.insertShareWidget(id,did,st);
      }, 0);
    }
  }};
  d.documentElement.appendChild(js);
}(document,"ok_shareWidget","http://dev.ok.ru","{width:100,height:30,st:'rounded',sz:20,nt:1}");
</script></div>


</div>
            </li>
            <li class="f-l" style="width:34%;">
                <div class="b-text">
                    Время&nbsp;работы:<br />
                    Гостиница:&nbsp;круглосуточно<br />
                    Ресторан&nbsp;и&nbsp;доставка:&nbsp;с&nbsp;<span style="font-family:times new roman">10:00&nbsp;</span>до&nbsp;<span style="font-family:times new roman">23:00</span><br />
                    Зона отдыха:&nbsp;круглосуточно
                </div>
            </li>
            <li class="f-l" style="width:19%;">
               <div class="b-text">
                    Email:<br />
<!--                    reception@lyufari.com<br />-->
<!--                    head@lyufari.com-->
                   lyufari@mail.ru
                </div>
            </li>
             <li class="f-l" style="width:15%;">
                 <div class="b-cont">

                  +38&nbsp;(067)&nbsp;862&nbsp;86&nbsp;48<br />
                  +38&nbsp;(095)&nbsp;172&nbsp;72&nbsp;72
                </div>
            </li>
         </ul>
    <div class="cl"></div>
    <div class="footer-b-ots"></div>
    </div>
</div>
</div>
<div class="gr-footer"></div>
<div class="gallery display-none">
    <div class="p-f galery_back z_index_10000">
    </div>
    <div class="p-f z_index_10001 gall_position photo_gallery">
        <div class="top_left_arrow gal_arrow_left p-a">
            <div class="gal_arrow "></div>
        </div>
        <div class="top_right_arrow gal_arrow_right p-a gal_arrow_height_">
            <div class="gal_arrow gal_arrow_right_pos"></div>
        </div>
        <div class="p-a count-style-center">
            <div class="p-r">
                <div class="count_center" id="count"></div>
            </div>
        </div>
        <div class="f-r">
            <div class="close_photos_gal p-a " title="Закрыть (Esc)"></div>
        </div>
        <div class="p-r overflow-hidden photo_gallery">
            <div class="p-a preloader" id="preloader_gif"></div>
            <div id="for-map" class="text-align-c overflow-hidden"></div>
        </div>
        <div class="p-r">
            <div class="text-align-c">
                <div class="esc_gal">Навигация: стрелка влево, стрелка вправо, Esc</div>
                <div class="i4s" title="«4size» технология (от англ. size – размер; в переводе - «четыре размера») позволяет создавать веб-сайт, которые качественно отображаются и удобно читаются на всех популярных разрешениях экранов монитора.">
                </div>
            </div>
        </div>
    </div>
</div>
<!--	<div class="gallery display-none">-->
<!--    <div class="p-f galery_back z_index_10000"></div>-->
<!--    <div class="p-f z_index_10001 gall_position photo_gallery">		  -->
<!--   				   <div class="top_left_arrow gal_arrow_left p-a"><div class="gal_arrow "></div></div>	-->
<!--   				   <div class="top_right_arrow gal_arrow_right p-a gal_arrow_height_"><div class="gal_arrow gal_arrow_right_pos"></div></div>-->
<!--                   <div class="p-a right-zero bottom-zero">-->
<!--                        <div class="ic_fsize p-r"></div>-->
<!--                   </div>	-->
<!--   				    <div class="p-a count-style-center">-->
<!--   				    	 <div class="p-r">-->
<!--   				    		  <div class="count_center"  id="count" ></div>-->
<!--   				    	 </div>-->
<!--   				    </div>-->
<!--    		      <div class="f-r">-->
<!--                        <div class="p-a z_index_10001">-->
<!--                            <div class="close_photos_gal p-r" title="Закрыть (Esc)"></div>-->
<!--                        </div>-->
<!--                       -->
<!--                   </div>-->
<!--    		      	-->
<!--    		     	    <div class="p-r overflow-hidden photo_gallery">-->
<!--    		     	    	 <div class='p-a preloader' id='preloader_gif'></div>-->
<!--		    		    		<div id="for-map" class="text-align-c">-->
<!--		    		    	-->
<!--    		    		</div>-->
<!--    		    	</div>-->
<!--    		     	-->
<!--    		    	<div class="p-r">-->
<!--                        <div class='text-align-c'><div class="esc_gal" >Навигация: стрелка влево, стрелка вправо, Esc</div></div>-->
<!--                        -->
<!--                    </div>-->
<!--    		     -->
<!--   </div>-->
<!--</div>-->
<div class='pan display-none'>
    <div class="p-f galery_back z_index_10000"></div>
    <div class="p-f z_index_10001 gall_position photo_gallery">		  
   				   <div class="top_left_arrow gal_arrow_left p-a"><div class="gal_arrow "></div></div>	
   				   <div class="top_right_arrow gal_arrow_right p-a gal_arrow_height_"><div class="gal_arrow gal_arrow_right_pos"></div></div>
                   <div class="p-a right-zero bottom-zero">
                        <div class="ic_fsize p-r"></div>
                   </div>	
    		      <div class="f-r">
                        <div class="p-a z_index_10001">
                            <div class="close_photos_gal p-r" title="Закрыть (Esc)"></div>
                        </div>
                       
                   </div>
    		      	
    		     	    <div class="p-r overflow-hidden photo_gallery">
    		     	    	 <div class='p-a preloader'></div>
		    		    	<div class="pan-window">
                        		<div class='panorama-view photo_gallery overflow_hidden'>
                        		</div>
                        	 </div>
    		    	</div>
    		     	
    		    	<div class="p-r">
                        <div class='text-align-c'><div class="esc_gal" >Навигация: стрелка влево, стрелка вправо, Esc</div></div>
                        
                    </div>
    		     
   </div>
	 
</div>
