<?php 
$page->addscript('js/exaptionm.js');
?>
<div class="doc-el">
<div class="m-b">
    <div class="af-header"></div>
    <div><h1>Мероприятия</h1></div>
  
	<div class="rest-t" style="margin-top:25px;">Усадьба «Люфари» является гостиницей премиум класса и дарит своим <br />гостям максимум уюта и комфорта.</div>
    
	<div class="rest-t-sub-title font-style-italic margin-zero " style="margin-top:45px;">День рождения, юбилеи, торжества </div>
	
    
        
    
	
	<div class="f-l first_block_activiti" style="width:50%;">

	<div class="transfer-t font-style-normal margin-zero" style="margin-top:24px;">   Ищете уютное место, где можно отлично провести время, наслаждаясь вкусом нежнейшего мяса, свежайших морепродуктов и изысканного вина?  </div>
	
	<div class="transfer-t font-style-normal margin-zero" style="margin-top:30px;">Тогда Вы оказались здесь неслучайно! <a href="/rus/restaurant">В ресторане «Люфари» </a>  можно насладиться блюдами всех регионов Италии, а  молодой и талантливый шеф-повар, не перестанет удивлять Вас своими «новинками» блюд, рецепты которых он привозит со всего мира. Ресторан имеет свое собственное производство пасты, популярного итальянского ликера  «Лимончелло» и прочих вкусностей. </div>
	 </div>
	 <div class="f-r first_block_activiti " style="width:45.5%;">
	 <div class="transfer-t font-style-normal margin-zero" style="margin-top:24px;">  Ресторан удобен для проведения, как деловых приемов, так и семейных торжеств, а так же круглосуточно готов порадовать Вас изысканной кухней или доставить блюдо в любую точку города. Персонал усадьбы «Люфари» с радостью возьмет на себя все заботы об организации и проведении мероприятий: широкий выбор шоу-программ, музыкальное сопровождение, любые блюда по Вашему пожеланию - все это создаст неповторимую атмосферу праздника!</div>
</div>
	 <div class="cl"></div>
	 <div class="f-l activiti_block" >
	<div class="rest-t-sub-title font-style-italic margin-zero" style="margin-top:83px;">Детский день рождения</div>
	
	<div class="f-l img_activiti" style="width:20.5%; margin:20px 6% 0 1%;">
            <img class="width-h-p" style='' src="../img/activiti_h_b.png" />
     </div>
     <div class="f-l" style='width:72%;margin-top:25px'>
            <div class="transfer-t font-style-normal margin-zero">
							   Подарите ребенку мечту! Малышу – волшебную кулинарную сказку 
								с&nbsp;шеф-поваром, школьнику – захватывающая шоу программа, подростку 
								– вечеринку в стиле ночного клуба. Любой праздник в усадьбе Люфари – 
								это радость, веселье, удивление и восторг, но главное – прекрасные 
								воспоминания на долгие годы!
			</div>
    </div>
	<a name="s_p_k"></a>
	<div class="cl"></div>
	<a name="s_p_k"></a>
		<div class="rest-t-sub-title font-style-italic margin-zero"  style="margin-top:57px;">Свадьба под ключ</div>
	
	<div class="f-l img_activiti" style="width:28.9%; margin:5% 3%  0 2%;">
            <img class="width-h-p" style='' src="../img/activiti_s_k.png" />
     </div>
     <div class="transfer-t font-style-normal margin-zero" style="margin-top:25px;">Лучше всего организованная свадьба это исключительно свадьба под ключ. При организации свадеб усадьба «Люфари» полностью берет на себя ответственность за все происходящее от начала и до конца. Мы сможем воплотить все ваши фантазии в реальность и сделать свадьбу незабываемым событием, о котором вы будете вспоминать всю свою жизнь. Гости будут в восторге! Позвольте нам сделать Вашу свадьбу праздником всей жизни!</div>
	
	
		<div class="cl"></div>
		<div class="rest-t-sub-title font-style-italic margin-zero"  style="margin-top:66px;">Бизнес конференции и семинары, презентации.</div>
	
	<div class="f-l img_activiti" style="width:21.2%; margin:5% 3%  0 0;">
            <img class="width-h-p" style='' src="../img/activiti_c_b.png" />
     </div>
    
            <div class="transfer-t font-style-normal margin-zero" style="margin-top:25px;">
						Современный деловой мир неустанно наполняется новыми компаниями, организациями, предприятиями. Вместе с этим непрерывно идет установление деловых контактов, что невозможно без проведения таких мероприятий как конференция, семинар, тренинг. Эти мероприятия всегда направлены на достижения успешного развития компании. Организации 
						конференции, семинара или тренинга является своего рода визитной карточкой той или иной компании. Конференция стала важным элементом деловой жизни, поэтому появился новый вид услуг конференц-сервис VIP-класса, который предоставляет усадьба «Люфари».
			</div>
			
		<ul class="activiti_ul" style="margin-top:20px;">
			<li>Уютный зал ресторана а, так же комната переговоров, оборудованная по последнему слову техники, для проведения конференции, семинара или тренинга;</li>
		   <li>Оформление конференц-залов и комнат для переговоров;</li>
		   <li>Специальное оборудование для проведения пресс-конференций и мероприятий обучения;</li>
		   <li>Решение всех организационно–бытовых вопросов, связанных с участием в мероприятиях;</li>
			<li>Организация расселения участников конференции в номерах гостиницы различной категории комфортабельности;</li>
			  <li>Подготовка презентационных и раздаточных материалов конференции, семинара или тренинга;</li>
			   <li>Проведение кофе-брейка, фуршета, банкета способствует установлению более тесных контактов и обсуждению тех или иных вопросов между участниками конференции.</li>
		</ul>
</div>
<div class="f-r activiti_block_r" >
	<div class="cl"></div>
	
	
	<div class="rest-t-sub-title font-style-italic margin-zero" style="margin-top:84px;">Выпускные вечера</div>
	<br/>
	<div class="f-l img_activiti" style="width:18.5%; margin-right:4.2%;">
            <img class="width-h-p" style='' src="../img/activiti_v_v.png" />
     </div>
     <div class="f-l" style='width:73%; margin-top:7px;'>
            <div class="transfer-t font-style-normal margin-zero">
							Есть праздники, которые невозможно повторить! И выпускной вечер – один из них. А нам под силу сделать его не просто запоминающимся, а таким, чтобы, встретившись с одноклассниками через 20 лет, Вы сказали: наш праздник был самым лучшим!
			</div>
    </div>
	<div class="cl"></div>
	 <div class="rest-t-sub-title font-style-italic margin-zero" style="margin-top:83px;">Календарные праздники</div>
	
	<div class="f-l img_activiti" style="width:19.2%; margin:20px 2.4% 0 0;">
            <img class="width-h-p" style='' src="../img/activiti_k_p.png" />
     </div>
     <div class="f-l" style='width:78.4%;margin-top:25px'>
            <div class="transfer-t font-style-normal margin-zero">
							  31 декабря, 8 Марта, 23 февраля, 14 февраля, 1 Мая – для всех нас это не просто даты, а самые любимые праздники в году! Почему любимые? Потому, что они касаются всех без исключения и каждому приносят теплые воспоминания из детства. Так давайте же отпразднуем их так, чтобы к милым детским впечатлениям добавились новые – яркие, свежие и незабываемые воспоминания об усадьбе Люфари!
			</div>
    </div>
	 <div class="cl"></div>
	 <div class="rest-t-sub-title font-style-italic margin-zero" style="margin-top:83px;">Спортивные мероприятия</div>
	
	<div class="f-l img_activiti" style="width:26.4%; margin:20px 3.4% 0 0;">
            <img class="width-h-p" style='' src="../img/activiti_s_m.png" />
     </div>
     <div class="f-l" style='width:69.4%;;margin-top:25px'>
            <div class="transfer-t font-style-normal margin-zero">
							Азарт соревнований, вкус победы, рекорды и титулы – ради всего этого мы и ходим на спортивные соревнования. А еще – ради яркой церемонии открытия, неординарного шоу и трогательного финала любого турнира. Наверное, улетающего олимпийского мишку помнят все?  Мы сделаем так, что яркие моменты Ваших турниров запомнятся настолько же долго!
			</div>
    </div>
	<div class="cl"></div>
	 <div class="rest-t-sub-title font-style-italic margin-zero" style="margin-top:83px;">Тим-билдинг</div>
	
	<div class="f-l img_activiti" style="width:18.5%;; margin:20px 7% 0 1%;">
            <img class="width-h-p" style='' src="../img/activiti_t_b.png" />
     </div>
     <div class="f-l" style='width:69.4%;;margin-top:25px'>
            <div class="transfer-t font-style-normal margin-zero">
							Усадьба Люфари предлагает кулинарный тим-билдинг! Выездное мероприятие запоминается всем работникам как большое корпоративное событие, что улучшает их отношение к компании, ее руководству и работе в целом. Смена обстановки помогает сотрудникам стать одной командой и взглянуть 
			</div>
    </div>
	<div class="cl"></div>
	 <div class="cl"></div>
		<div class="rest-t-sub-title font-style-italic margin-zero"  style="margin-top:66px;">Семейные кулинарные вечера.</div>
	
	<div class="f-l img_activiti" style="width:39%;; margin:5% 5%  0 0;">
            <img class="width-h-p" style='' src="../img/activiti_s_v.png" />
     </div>
     <div class="transfer-t font-style-normal margin-zero" style="margin-top:34px;">Ресторан усадьбы «Люфари» предлагает семейные развлекательные вечера: кулинарные соревнования, шоу программы от шеф-повара, розыгрыши призов и веселые конкурсы. Каждый 
гость может не только ознакомиться с секретами поварского мастерства, но и весело провести время в кругу семьи!</div>
	<div class="cl"></div>
	 </div>
</div>
</div>