<?php
//$page->addScript('js/exaptionm.js','js/jquery.panorama.js','js/jquery.deliv.js'/*'js/jquery.gal.static.js',*//*,'js/mask-phone.js'*/,'js/jquery.form.js','js/jquery-ui_1.9.1.js','js/date.js');
$page->addCss('css/jquery-ui-1.9.1.css');
//$page->addScript('js/mask.js','js/jquery.deliv.js');
$page->addScript('js/exaptionm.js','js/jquery.deliv.js','js/jquery.panorama.js','js/jquery.form.js','js/jquery.mousewheel.min.js','js/jquery-ui_1.9.1.js','js/date.js','js/jquery.panoramaelse.js','js/mask.js','js/jquery.bron.js');
?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel').jcarousel({
            /* wrap: 'circular',*/
            visible: 5,
            scroll: 1
        });


    });
 /*   $(function(){

        if ($.browser.opera) $('.preload').css('display','none').fadeIn(600)
        else
            $('.preload').css('display','none').load(function(){
                $(this).fadeIn(600)
            })

    });*/

</script>


<script type="text/javascript">
$(document).ready(function(){
    $('.submainname').addClass('disp_none')

    console.log('2')
})
    $(document).on('click touchend','.menu-punkt-hover',function(){

        if ($(this).hasClass('backbottom'))
        {
        $(this).parent().find('.submainname').addClass('disp_none')

        }
        else
        {
            console.log('2')
        $(this).parent().find('.submainname').removeClass('disp_none')

        }
    })




</script>
<div class="m-b">
<div class="mar_40">
<div class="cl"></div>
<div class="af-header"></div>

<h1 class="title" style="margin-bottom: 14px;">Экскурсии по донецку и донецкой области</h1>

<div class="rest-lu-block-pan-cont" style="height:399px">

    <div class="panorama">

        <div id="fo-map" class="border_gray">
            <div class="panorama-view">
                <div class="panorama-container">
                    <img src="../img/pan/exursion.jpg" data-width="1900" data-height="399" data-timeout="100" class="preload position_absolute left_zero" alt="" />
                </div>
            </div>
        </div>

        <div class="p-r" style="width: 100%;margin-top:-34px;">
            <div style="background: url('../img/panoram_line.png') no-repeat;width:529px;margin:0 auto;height:9px;"></div>
            <div style="width:529px;margin:0 auto;">
                <div class="pandelim p-r" style="left:0;"></div>

            </div>
            <div class='panline p-r width-h-p' style="margin:0 auto;height:35px;top:-54px;">
                <div style="width:529px;margin:0 auto;height:100%"></div>
            </div>
        </div>
    </div>

</div>


<div class="cl"></div>
<div class="menu-container page_restarea">
    <div class="menu-inside-container">
        <p style="margin-bottom: 0 !important;">Вы сможете заказать любую заинтересовавшую Вас экскурсию по контактным телефонам: +38 (067) 862 86 48,  +38 (095) 172 72 72</p>
    </div>
</div>



<div class="cl"></div>
<div class="mezhblocs"></div>

    <div class="title_text_restarea" style="margin-bottom: -35px;margin-top: -14px;"><span class="rest_title_left"></span>Перечень ЭКскурсий<span class="rest_title_right"></span></div>
<div class="menu-container p-r" style="background: none">

        <div class="menu-inside-container">

            <div class="cl"></div>
            <div class="cl"></div>
            <div class="menu-ul excursiob" style="background: white;">

                <form method="post">



                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l ">Обзорная экскурсия по Донецку</div>

                        </div>
                        <div class="submainname menu-delim  " style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text" >В ходе этой экскурсии Вы ознакомитесь с достопримечательностями, которые находятся на центральных улицах города: Артема, Университетской, Челюскинцев, бульваре Пушкина.</div>
                            <div class="text" >Вы увидите площадь Ленина, Донецкий областной краеведческий музей, пальму Мерцалова, монумент "Твоим освободителям, Донбасс!", терриконы, здание городского совета, парк кованых фигур – единственный в Европе, памятники Сергею Бубке, Иосифу Кобзону, Анатолию Соловьяненко, театр оперы и балета, драматический театр, здание первой гостиницы Донецка, а также здания Донецкой филармонии и консерватории. Вы полюбуетесь прекрасным видом на реку Кальмиус, увидите Царь-пушку, архангела Михаила, Бохумский колокол. Вы ознакомитесь со старой Юзовкой (первое название г. Донецка), увидите дом Кроля – основателя наружной рекламы в Донецке. И, конечно же, бульвар Пушкина – жемчужина Донецка – не останется без внимания. После посещения Свято-Преображенского кафедрального собора Вам будет показан уголок Великобритании в Донецке.</div>
                           <br/> <div class="text" >Продолжительность экскурсии: 3 - 3,5 часа.</div>

                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="second-carousel" class=" first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/2.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/obzor_doneck/" src='../img/photos/excursion/obzor_doneck/prew/7.jpg'/>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                        <div class="cl"></div>



                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия "Сады, парки, бульвары г. Донецка"</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                             <div class="text">Наш город удивительно зеленый, хотя и построен в безлесной степи. Парки, скверы, бульвары радуют глаз. А по количеству роз на душу населения мы были первыми в мире еще в 1978 году. Тогда же и была вручена Донецкому ботаническому саду золотая медаль ЮНЕСКО за работы по промышленному озеленению.</div>
                            <div class="text">Донецкий ботанический сад основан Национальной академией наук Украины в 1964 году как центр по разработке фундаментальных и прикладных проблем биологии на юго-востоке Украины. Площадь сада составляет 270 га (первое место по площади в Европе). На его территории произрастает около пяти с половиной тысяч видов растений. Под стеклом находится 1200 кв. м площади, что позволило организовать 5 оранжерей и сымитировать условия тропиков и субтропиков. В ходе экскурсионной программы Вы посетите самые живописные места Донецка: обновленный парк культуры и отдыха им. Щербакова, бульвар Пушкина, бульвар Шевченко, парк гостиницы "Виктория", парк стадиона "Донбасс-Арена", ботанический сад, набережную реки Кальмиус, парк кованых фигур. Узнаете об истории их возникновения, сделаете незабываемые фото на память.</div>
                            <br/><div class="text">Продолжительность экскурсии: 3 часа.</div>

                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия "Донецкие истоки"</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Экскурсионная программа ознакомит вас с историей возникновения нашего города. Вы побываете в одном из старейших районов Донецка, бывшей северной части города – Новом Свете. Здесь сохранились здания конца IIX – начала XX веков: дом Кроля, гостиница Великобритания, аптека Лаче, дом Горелика, Братская школа и другие здания.</div>
                            <div class="text">Вы посетите музей Донецкого металлургического завода, где отражена его история, тесно связанная с историей возникновения и развития города Донецка. На территории завода Вы посетите православный храм святителя Игнатия Мариупольского.</div>
                            <br/> <div class="text">Продолжительность экскурсии: 3 часа.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="third-carousel" class="first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel  jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/2.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/istoki_donecka/" src='../img/photos/excursion/istoki_donecka/prew/7.jpg'/>
                                        </li>

                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия "По страницам прекрасного"</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Для ценителей искусства посещение этой экскурсии обязательно. Если Вы поклонник творчества Айвазовского, Шишкина, Фалька, Крыжицкого, интересуетесь современным искусством Украины и Европы, Вы обязательно должны побывать на этой экскурсии. Вместе мы посетим Донецкий областной художественный музей, галерею современного искусства "Арт - галерея 13" и "Арт-Донбасс", салон-галерею современной итальянской живописи “Paduano-Arte”, бульвар Пушкина.</div>
                            <div class="text">Бульвар Пушкина – это свой маленький Арбат в Донецке. Расположен между двумя главными улицами города – ул. Артема и ул. Университетской. На бульваре каждый день проходит выставка-продажа картин донецких художников. Здесь можно купить произведения искусства и старинные вещи, нарисовать свой портрет или шарж. А в заключение экскурсии мы прогуляемся парком скульптур "Украинская степь".</div>
                            <br/><div class="text">Продолжительность экскурсии: 3 часа.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="four-carousel" class=" first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/2.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/po_str_prekrasnogo/" src='../img/photos/excursion/po_str_prekrasnogo/prew/7.jpg'/>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия "Донецк спортивный"</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Экскурсионная программа ознакомит Вас со спортивной жизнью города, с достижениями наших выдающихся земляков, с крупнейшими спортивными сооружениями Донецка. Вы посетите первый стадион в Восточной Европе, спроектированный и построенный в соответствии со стандартами УЕФА категории «Элит» (пять звезд) - «Донбасс Арена», музей футбольной команды "Шахтер", памятник Сергею Бубке, РСК "Олимпийский" и другие достопримечательности.</div>
                            <br/> <div class="text">Продолжительность экскурсии: 2 - 3 часа.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="first-carousel" class="first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/2.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/doneck_sportivniy/" src='../img/photos/excursion/doneck_sportivniy/prew/7.jpg'/>
                                        </li>

                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия "Донецк православный"</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Экскурсионный тур ознакомит Вас с миром православной культуры и историей русской православной церкви. Вы узнаете много интересного о церковной жизни Донецка, о православных подвижниках, храмах и соборах города. Вы побываете в Свято-Николаевском кафедральном соборе, храме Святителя Игнатия Мариупольского, храме Рождества Христова, Спасо-Преображенском кафедральном соборе, а также в женском Свято-Иверском монастыре. Увидите часовню Святой Варвары, Свято-Воскресенский храм, храм Святого Александра Невского и много других экскурсионных объектов.</div>
                            <br/><div class="text">Продолжительность экскурсии: 5 часов.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="six-carousel" class=" first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/2.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/doneck_pravoslavniy/" src='../img/photos/excursion/doneck_pravoslavniy/prew/7.jpg'/>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсии на Артемовский завод шампанских вин</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Город Артемовск - один из старейших городов Донбасса, был основан еще в 1571 году и имеет богатую историю. На территории города находятся богатые залежи каменной соли, огнеупорных и керамических глин, чистых гипсов, формовочных песков. Громкую известность Артемовску принес Артемовский завод шампанских вин.</div>
                            <div class="text">Артемовский завод шампанских вин – самое крупное в Восточной Европе предприятие по производству игристого вина традиционным бутылочным способом. Проверенные временем французские традиции производства шампанского и новейшие технологии и оборудование позволяют производить игристое вино по качеству сопоставимое с продукцией лучших мировых производителей шампанского.</div>
                            <div class="text">Артемовский завод шампанских вин - единственный в мире, где все производство находится под землей. На глубине 75 метров в природных условиях при постоянной температуре и влажности воздуха шампанское производится по классической французской технологии. Температура и влажность здесь постоянны, вне зависимости от времени года. А общая площадь подземных штолен составляет свыше 26 га, где одновременно хранится более 30 млн. бутылок артемовского вина. Из поколения в поколение бережно передаются драгоценный опыт, знания и секреты артемовских виноделов. Ориентация на потребителя, единство команды и ценность каждого сотрудника – главные принципы Артемовского завода шампанских вин.</div>
                            <div class="text">Во время экскурсии нас проведут по подземным галереям, познакомят с технологией производства божественного напитка от купажа до цеха отделки и упаковки. После этого, нас ожидает выставочный зал с дегустацией. На дегустацию предлагается 5-7 сортов шампанского производимого на заводе.</div>
                             <div class="text">В стоимость тура входит:<br/>
                                1. Проезд Донецк – Артемовск - Донецк;<br/>
                                2. Обзор исторических и культурных достопримечательностей по маршруту;<br/>
                                3. Осмотр всемирно известного завода шампанских вин, винных погребов, подземных заводских цехов переработки и изготовления шампанского, шахт-хранилищ, цеха упаковки;<br/>
                                4. Дегустация 5-7 сортов шампанского;<br/>
                                5. Страховка.</div>

                            <br/>     <div class="text">Продолжительность экскурсии: 5 часов.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="five-carousel" class=" first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/2.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/artemovskiy_zavod/" src='../img/photos/excursion/artemovskiy_zavod/prew/7.jpg'/>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>

                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсии в соляные шахты г. Соледара</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Соляное дело – один из самых первых промыслов в Древней Руси. Существуют сказки и легенды о соли. Бывали времена, когда соль ценили на вес золота. Среди соленосных регионов особое место занимает юго-восточная часть Донбасса, где на месте плескавшегося 250 млн. лет назад мелководного залива древнего Пермского моря образовались огромные залежи чистейшей каменной соли. Туристы со всего мира едут в Соледар, чтобы увидеть знаменитые соляные шахты. Оны занесены в список мирового культурного наследия ЮНЕСКО.</div>
                            <div class="text">Вам представляется уникальная возможность:<br/>
                                посетить чарующие лабиринты подземного соляного царства;<br/>
                                увидеть волшебные соляные скульптуры, сделанные руками народных умельцев;<br/>
                                пробежаться по соляному футбольному полю;<br/>
                                послушать симфоническую музыку в уникальном концертном зале;<br/>
                                узнать много интересного о чудодейственных свойствах соли;<br/>
                                получить сеанс солетерапии.</div>
                            <div class="text">Начинается экскурсия с краткого инструктажа по технике безопасности. Маршрут экскурсии проходит по отработанным галереям рудника №1-3, в камере №41–бис, расположенной в толще Подбрянцевского пласта на глубине 300 м. Стены, потолок, полы, фигуры и деревья – все здесь из соли. В огромных кристаллах соли находят и до сих пор оттиски и слепки птиц и рыб, населявших Землю миллионы лет назад. Воздух соляных пещер уникален, он насыщен мельчайшими частицами соли, что создает приятный микроклимат, благоприятно влияющий на самочувствие посетителей. Влажность воздуха - 60%, температура - 14-16 °С. Даже разовое посещение соляных пещер даст Вам прекрасный заряд положительных эмоций и энергий.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="sev-carousel" class=" first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/2.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/soledar/" src='../img/photos/excursion/soledar/prew/7.jpg'/>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Святогорская лавра</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Святогорск – известный климатический курорт Донбасса, раскинувшийся на живописных берегах Северского Донца.</div>
                            <div class="text">Он славится удивительной природой и уникальным историко-архитектурным наследием, несущим на себе печать седой древности, средневековья, память революционных бурь и Великой Отечественной Войны. Чарующая природа Святогорска вызывала восхищение у многих русских и украинских писателей, художников и композиторов, побывавших здесь в свое время. Антон Павлович Чехов восторгался необычайной красотой этого уголка, назвав его «Донецкой Швейцарией».</div>
                            <div class="text">Символом Святогорска является государственный историко-архитектурный заповедник, основанный в 1980 году постановлением правительства Украины. Основу комплекса памятников заповедника составляет архитектурный ансамбль XVII-XIX ст. - Святогорская Свято-Успенская Лавра, которая расположилась на живописном берегу Северского Донца в местности с историческим названием — Святые Горы.</div>
                            <div class="text">Свято-Успенская Святогорская лавра является духовным центром Донбасса и всей Восточной Украины. Многовековая история монашеской обители дала миру множество святых, а также уникальный историко-архитектурный комплекс, сочетающий естественные природные элементы и творение рук человеческих. Ныне насельниками Святогорской лавры не только восстанавливаются и реставрируются памятники XVII-XIX веков, но и создаются новые.</div>
                            <div class="text">Тысячи паломников и туристов посещают Святогорск. Ежегодно усиливается всеобщий интерес к его загадочному прошлому и событиям, происходившим здесь, к изучению и осознанию их исторической и культурной значимости.</div>
                            <div class="text">Программа этого тура поможет ощутить особую атмосферу Святогорска и увидеть такие места: гостиничный двор Свято-Успенской обители, Успенский собор - главный храм Свято-Успенской лавры, Покровскую церковь с колокольней, Пещерный комплекс, Кирилло-Мефодиевскую лестницу, Николаевскую церковь, Андреевскую часовню. А также вместе с Вами мы посетим место захоронения затворника святого Иоанна Святогорского, мемориал Великой Отечественной войны, монумент большевику-революционеру Артему, дуб Камышева.</div>
                            <div style="position: relative;margin-top: 15px;">
                                <div class='width-h-p' >


                                    <ul id="eight-carousel" class=" first-and-second-and-third-and-four-and-five-and-six-and-sev-and-eight-carousel jcarousel-skin-tango menu-gal-restarea width-h-p" style="display: block">
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/1.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/2.jpg'/>
                                        </li>
                                        <li>
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/3.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/4.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/5.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/6.jpg'/>
                                        </li>
                                        <li >
                                            <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/excursion/svyatogorskaya_lavra/" src='../img/photos/excursion/svyatogorskaya_lavra/prew/7.jpg'/>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cl"></div>
                            </div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия в Никольский монастырь</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">Село Никольское – очень красивое, духовное, умиротворенное место. Говорят, очень давно, еще до революции, Никольское освятила Своим присутствием Пресвятая Богородица. И на месте Ее явления, среди бескрайних донецких степей, забил целебный источник, а на месте двух скромных деревянных сельских храмов, Свято-Николаевского и Свято-Васильевского, в Никольском были воздвигнуты два роскошных каменных.</div>
                            <div class="text">После октябрьского переворота Свято-Николаевский храм разрушили, Свято-Васильевский закрыли. Но благочестивый народ еще долго служил запретные молебны на источнике Богородицы…Именно тогда в Никольском зародилось предание: когда в полуразрушенный Свято-Васильевский храм приедет служить монах, в Никольском откроются две обители. Так и случилось. Отец Зосима приехал в 1986 году в полуразрушенный храм без иконостаса и в обгоревший сарай вместо священнического домика. Его трудами храм был отреставрирован, построена крестильня с настоятельскими покоями и паломническая с трапезной.</div>
                            <div class="text">В 2001 году Свято-Николаевской сестринской общине села Никольское был дан статус монастыря, в 2002 году - зарегистрирован Свято-Васильевский мужской монастырь. По праву село Никольское называют островом надежды. Обитель посещают группы паломников из многих епархий Украины и России.</div>
                            <div class="text">В экскурсию программу по монастырю входит осмотр Свято-Васильевского храма, храма Николая Чудотворца, трапезного храма всех Святых, святого источника, домика и усыпальницы основателя монастыря батюшки Зосимы. В Васильевском храме хранится более 200 частиц святых мощей, собранных со всего православного мира, чудотворные иконы: святого великомученика и целителя Пантелеимона с частицей его мощей, чудотворная икона Божьей матери «Скоропослушница», чудотворная икона святого праведного отца Иоанна Кронштадского. Также вы насладитесь вкуснейшим монастырским обедом в трапезной для паломников.</div>

                            <div class="text"> В стоимость тура входит:<br/>
                                1. Проезд Донецк - Никольское – Донецк;<br/>
                                2. Обзор исторических и культурных достопримечательностей по маршруту;<br/>
                                3. Экскурсионная программа в с.Никольское;<br/>
                                4. Обед в монастырской трапезной;<br/>
                                5. Страховка.</div>
                            <br/><div class="text">Продолжительность тура: 6-7 часов.</div>
                            <div class="cl"></div>
                        </div>

                    </li>

                    <li class="mainname menu-delim">
                        <div class="menu-punkt-hover backbottom ">
                            <div class="menu-arrow-big f-l "></div>
                            <div class="menunamebackpad f-l  ">Экскурсия к источнику Николая Чудотворца</div>

                        </div>


                        <div class="cl"></div>

                        <div class="submainname menu-delim" style="margin-left: 42px;margin-right: 42px;padding-right: 10px;">
                            <div class="text">В реестре чудотворных источников Российской империи Авдеевский источник Николая Чудотворца датируется 1700 г. По легенде, здесь многократно наблюдали явление Николая Чудотворца. В 1930 г. активисты "Союза Безбожников" засыпали этот источник, но он пробился вновь. Было еще несколько попыток его уничтожить, но источник существует до сих пор и является местом паломничества верующих. Над источником сооружена часовня Божьей Матери "Споручницы Грешных".</div>
                             <div class="text"> В стоимость тура входит:<br/>
                                 1. Проезд Донецк - Авдеевка – Донецк;<br/>
                                 2. Обзор исторических и культурных достопримечательностей по маршруту;<br/>
                                 3. Страховка.</div>

                            <div class="cl"></div>
                        </div>

                    </li>
                </form>
            </div>
            <div class="cl"></div>







        </div>
    </div>

<div class="cl"></div>



</div>
</div>

<div class="cl"></div>

