<?php
$page->addScript('js/exaptionm.js','js/jquery.panorama.js','js/jquery.form.js','js/jquery.mousewheel.min.js','js/jquery-ui_1.9.1.js','js/date.js','js/jquery.panoramaelse.js');
$page->addCss('css/jquery-ui-1.9.1.css');

?>
<script type="text/javascript">

    jQuery(document).ready(function() {

        $('.scroll').css({display:'none'})



        var img_src = $('.scroll').attr('src')


        var img = new Image();
        img.src = img_src;

        img.onload =function(){

            $('.scroll').fadeIn(800)


        }



        jQuery('#mycarousel').jcarousel({
            wrap: 'circular',
            visible: 5,
            scroll: 1
        });
    });

var with_img,width_x

   /* $(window).bind('scroll',function(e){
        parallaxScroll();
    });

    function parallaxScroll(){
        var height_img = $('.scroll').height()
        var scrolled = $(window).scrollTop();
        var move_top = 0-(scrolled*.99)

        if ( (height_img - 480) > ((move_top)*-1) )
        {
            $('.scroll').css('top',(move_top)+'px');
        }


    }*/



</script>

<div class="doc-el">
<div class="m-b ">
<div class="mar_40">
<div class="cl"></div>
<div class="af-header"></div>
<h1 class="title" style="margin-bottom: 14px;">Усадьба Люфари</h1>





        <div class="border_gray " style="position: relative;overflow: hidden;" >
<div style="height:812px;width:100%">
                    <img class="scroll"  src="../img/main_new.png" style="width: 100%;"/>
</div>
        </div>







<div class="cl"></div>
<div class="menu-container page_restarea">
    <div class="menu-inside-container">
        <p>Гостинично-ресторанный комплекс «Люфари» расположен в спокойной части делового центра города Донецка. Благодаря удобному расположению усадьбы Вы легко доберетесь до аэропорта, железнодорожного вокзала, спортивных стадионов, бизнес-центров и других достопримечательностей города. </p>
    </div>
</div>






<!-- -->

    <p class="in_main " style="float: left">Гостиница</p>
    <p class="in_main " style="float: right" >Спа</p>
    <p class="in_main f_r" style="margin: 0 auto; margin-top: 28px ;">Ресторан</p>

    <div class="clear"></div>
<div class="main_block f">

    <img src="../img/main_1.png"/>


    <div class="vert_al" style="width: 100%;height: 100%;position: relative;z-index: 1;">

        <a class="maina bany" href="/delux" >НОМЕРА&nbsp;ДЕ&nbsp;ЛЮКС</a><br/>
        <a  class="maina "href="/apartment" >Апартаменты</a><br/>

    </div>



</div>

    <div class="main_block t">


       <img src="../img/main_3.png"/>
        <div class="vert_al" style="width: 100%;height: 100%;position: relative;z-index: 1;">

        <a class="maina" href="/restarea/bath" >Баня&nbsp;на&nbsp;дровах</a><br/>
                <a  class="maina" href="/restarea/hamam" >Турецкий&nbsp;хамам</a><br/>
                <a class="maina " href="/restarea/banquet" >Мини<br/>банкетный&nbsp;зал</a>
        </div>
    </div>

    <div class="main_block s">

        <a  href="/restaurant" style="display: block !important;"><img src="../img/main_2.png"/></a>
    </div>

    <div class="clear"></div>
    <div class="main_text">
        <img src="../img/main_text.png"/>
    </div>

</div>
</div>

<div class="cl"></div>



<script type="text/javascript">
    function restareaphotos()
    {
        var w=('innerWidth' in window) ? window.innerWidth : document.body.offsetWidth;
        /*if(w>=1280)
         {
         $('.menu-gal-restarea li').each(function(i)
         {
         if(i!=0 && (i+1)%3==0)
         {
         $(this).addClass('margin-zero').removeClass('little')
         }
         })
         }
         else
         {
         $('.menu-gal-restarea li').removeClass('margin-zero').addClass('little')
         }*/
        if(w<=1000)
        {
            $('.top-rest-area').addClass('small')
            $('.top-rest-area .ic_hamam,.top-rest-area .ic_bany,.top-rest-area .ic_zal').addClass('small')
        }
        else
        {
            $('.top-rest-area').removeClass('small')
            $('.top-rest-area .ic_hamam,.top-rest-area .ic_bany,.top-rest-area .ic_zal').removeClass('small')
        }
    }
    $(function()
    {
        restareaphotos()
    })
    $(window).resize(function()
    {
        restareaphotos()
    })
</script>


