<?php 
    $page->addScript('js/exaptionm.js','js/jquery.panorama.js','js/jquery.deliv.js',/*'js/jquery.gal.static.js',*/'js/mask.js'/*,'js/mask-phone.js'*/,'js/jquery.form.js','js/jquery-ui_1.9.1.js','js/date.js');
    $page->addCss('css/jquery-ui-1.9.1.css');

?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#mycarousel').jcarousel({
            /* wrap: 'circular',*/
            visible: 5,
            scroll: 2
        });
    });
$(function(){

//     if ($.browser.opera) $('.preload').css('display','none').fadeIn(600)
//       else
//      $('.preload').css('display','none').load(function(){
//            $(this).fadeIn(600)
//        })
//
});
</script>
<div class="m-b">
<div class="mar_40">
 <div class="cl"></div>
 <div class="af-header"></div>

 <h1 class="title" style="margin-bottom: 14px;">Ресторан “ЛЮфари”</h1>

 <div class="rest-lu-block-pan-cont" style="height: 400px">

     <div class="panorama">

         <div id="fo-map" class="border_gray">
             <div class="panorama-view">
                 <div class="panorama-container">
                     <img src="../img/pan/restoran_new.jpg" data-width="2814" data-height="400" data-timeout="100" class="preload position_absolute left_zero" alt="" />
                 </div>
             </div>
         </div>

         <div class="p-r" style="width: 100%;margin-top:-34px;">
             <div style="background: url('../img/panoram_line.png') no-repeat;width:529px;margin:0 auto;height:9px;"></div>
             <div style="width:529px;margin:0 auto;">
                 <div class="pandelim p-r" style="left:0;"></div>

             </div>
             <div class='panline p-r width-h-p' style="margin:0 auto;height:35px;top:-54px;">
                 <div style="width:529px;margin:0 auto;height:100%"></div>
             </div>
         </div>
     </div>

 </div>


 <div class="cl"></div>
 <div class="menu-container page_restarea">
     <div class="menu-inside-container">
         <p>Люфари – это новый уровень среди ресторанов Донецка.  Уютный зал на 50 человек позволит провести незабываемое торжество, детский праздник или просто дружескую встречу.</p>
         <p>Только здесь Вы сможете отведать блюда по старинным итальянским рецептам. Наш шеф-повар порадует Вас моцарелой и пастой собственного приготовления, что даст Вам возможность оценить истинный вкус Италии.</p>
         <p>Главная черта нашего ресторана – это внимательное и заботливое отношение  к каждому гостю. Мы делаем все возможное, чтобы частичка Вашей души осталась с нами.</p>
     </div>
 </div>


 <div style="position: relative;margin-top: 15px;">
     <div class='width-h-p' >


         <ul id="mycarousel" class="jcarousel-skin-tango menu-gal-restarea width-h-p" >
             <li>
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/rest/" src='../img/photos/rest/1.jpg'/>
             </li>
             <li>
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/rest/" src='../img/photos/rest/2.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/rest/" src='../img/photos/rest/3.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/rest/" src='../img/photos/rest/4.jpg'/>
             </li>
             <li>
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/rest/" src='../img/photos/rest/5.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/rest/" src='../img/photos/rest/6.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/rest/" src='../img/photos/rest/7.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="7" data-folder="img/photos/rest/" src='../img/photos/rest/8.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="8" data-folder="img/photos/rest/" src='../img/photos/rest/9.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="9" data-folder="img/photos/rest/" src='../img/photos/rest/10.jpg'/>
             </li>
             <li >
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="10" data-folder="img/photos/rest/" src='../img/photos/rest/11.jpg'/>
             </li>
         </ul>




         <!--ul class="menu-gal-restarea width-h-p">
              <li>
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/1.jpg'/>
             </li>
              <li>
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/2.jpg'/>
             </li>
             <li class='margin-zero'>
                 <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/3.jpg'/>
             </li>
             <li >
                  <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/4.jpg'/>
             </li>
             <li>
                  <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/5.jpg'/>
             </li>
             <li class="margin-zero">
                  <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/6.jpg'/>
             </li>
         </ul-->

     </div>
     <div class="cl"></div>
     <!--div class="rest-t" >Панорама 360&deg;</div>

			<div class="width-h-p p-r ">
							<div class="p-a gallery-ugol-left-top"></div>
                            <div class="p-a gallery-ugol-right-top"></div>
                            <div class="p-a gallery-ugol-left-buttom"></div>
                            <div class="p-a gallery-ugol-right-buttom"></div>
			<div class="areappan">
			<img alt="" data-swf="hamam.jpg" data-width="1530~1920~2400" data-height="459~576~720" data-360="1" class='virt width-h-p' src="/../img/photos/area/pan/hamam.jpg"/></div>
    </div--></div>
 <div class="cl"></div>
    <div class="cl"></div>
    <div class="mezhblocs"></div>





 <div class="title_text_restarea" style="margin-bottom: -35px;margin-top: -14px;"><span class="rest_title_left"></span>Меню ресторана «Люфари»<span class="rest_title_right"></span></div>
 <div class="cl"></div>
    <div class="menu-container p-r" style="background: none">

    <div class="menu-inside-container">
        <div class="menu-price-on f-l" style="margin-top: 32px;">Цены в грн. на <?php
         $sql="SELECT date FROM actual_date_price";
                                $db->query($sql);
                                if($db->getCount()>0)
                                {
                                    $date=$db->getValue();
                                    $date=explode('-',$date);
                                    echo $date[2].".".$date[1].".".$date[0];
                                }
        ?>
        </div>
        <div class="menu-price-on bigger f-r"><div class="total">Итого: 0грн</div><div class="price-for-delivery summ_zakaz">Сумма заказа для доставки: 0грн</div></div>
         <div class="cl"></div>
        <div class="menu-price-on f-l"><span class="menu-h-s-all show-all">Показать все</span><span class="menu-h-s-all mar-l hide-all">Скрыть все</span></div>
        <div class=" f-r free-delivery">Бесплатная доставка осуществляется свыше 250грн</div>
         <div class="cl"></div>
         <div class="menu-ul" style="background: white;">
    <?php
    echo "<form method='post'>";
    $array_of_category=array();
    $array_of_category_sub=array();
    $array_of_category_bludo=array();
    $q_cat = "SELECT * FROM menu_m WHERE parent=0 AND element_submenu = 1 AND invisible=0 ORDER BY name";  // отобрали категории
    $db->query($q_cat);
    if($db->getCount()>0)
    {
        $array=$db->getArray();
        foreach($array as $index=>$val)
        {
            $bluds_on_category="SELECT * FROM menu_m WHERE parent = ".$val['id']." AND name<>'' AND element_submenu = 1 AND invisible=0 ORDER BY prior";
            $db->query($bluds_on_category);
            if($db->getCount()>0)
            {
                $array_sub=$db->getArray();
                foreach($array_sub as $array_sub_index=>$array_sub_val)
                {
                    $sql_="SELECT * FROM menu_m WHERE  parent = ".$array_sub_val['id']." AND name<>'' AND element_submenu = 0 AND price<>'' AND weight<>'' AND invisible=0 ORDER BY name";
                    $db->query($sql_);
                    if($db->getCount()>0)
                    {
                        $array_of_category_sub=$db->getArray();
                        break;
                    }

                }
                //есть ли блюда просто в категории
                $sql_else="SELECT * FROM menu_m WHERE  parent = '$val[id]' AND name<>'' AND element_submenu = 0 AND invisible=0 AND price<>'' AND weight<>'' ORDER BY name";
                $db->query($sql_else);
                if($db->getCount()>0)
                {
                    $array_of_category_bludo=$db->getArray();
                }
            }
            if(count($array_of_category_bludo)>0 OR count($array_of_category_sub)>0)
            {
                array_push($array_of_category,$val);
            }
        }
    }
    $q_cat = "SELECT * FROM menu_m WHERE parent=0 AND element_submenu = 1 AND invisible=0 ORDER BY name";  // отобрали категории
    $db->query($q_cat);
	if(count($array_of_category)>0)
	{
	  $arr_prosto_bludo;
//	  $arr_main=$db->getArray();
      echo "<ul>";
          foreach($array_of_category as $arr_main_indexs=>$arr_main_val)
          {
                echo "<li class='mainname menu-delim'>";
                echo '<div class="menu-punkt-hover"><div class="menu-arrow-big f-l"></div><div class="menunamebackpad f-l">'.$arr_main_val['name'].'</div></div>';
                echo '<div class="cl"></div>';
                $q_sub ="SELECT * FROM menu_m WHERE parent = '$arr_main_val[id]' AND name<>'' AND element_submenu = 1 AND invisible=0 ORDER BY prior";

                $db->query($q_sub);
                if($db->getCount()>0)
                {
                    $arr_sub=$db->getArray();
                    echo "<ul>";

                    foreach($arr_sub as $arr_sub_index=>$arr_sub_val)
                    {
                        $sql_sub_sub="SELECT * FROM menu_m WHERE  parent = '$arr_sub_val[id]' AND name<>'' AND element_submenu = 0 AND price<>'' AND weight<>'' AND invisible=0 ORDER BY name";
                        $db->query($sql_sub_sub);
                        $count=$db->getCount();
                        if($count>0)
                        {
                            echo ($arr_sub_index==0)? "<li class='submainname' style='margin-left:10px;padding:0 10px 10px 10px'>":"<li class='submainname menu-delim' style='margin-left:10px;'>";
                            echo '<div class="menu-punkt-hover"><div class="menu-arrow-little f-l"></div><div class="menunamebackpad f-l active">'.$arr_sub_val['name'].'</div></div>';
                            echo '<div class="cl"></div>';
                        }

//                        $sql_sub_sub="SELECT * FROM menu_m WHERE  parent = '$arr_sub_val[id]' AND name<>'' AND element_submenu = 0 AND price<>'' AND weight<>'' AND invisible=0 ORDER BY name";
//                        $db->query($sql_sub_sub);
                        if($count>0)
                        {
                            $arr_sub_sub=$db->getArray();
                            echo "<ul class='width-h-p' style='margin:0px 0 0 0px'>";
                            echo '<li class="menu-th menu-delim"><div class="f-l menu-foto"></div><div class="f-l menu-f">Наименование</div><div class="f-r menu-fi">Доставка</div><div class="f-r menu-fo">Кол-во</div><div class="f-r menu-t">Цена</div><div class="f-r menu-s">Выход</div><div class="cl"></div></li>';
                            foreach($arr_sub_sub as $arr_sub_sub_index=>$arr_sub_sub_val)
                            {
                                echo '<li style="padding: 16px 0px 10px 10px" class="bludo">';
                                $sqlphoto='SELECT * FROM menuphoto WHERE parent='.$arr_sub_sub_val['id'].' AND temp=1 ORDER BY dtcreate DESC LIMIT 1';
                                $db->query($sqlphoto);
                                if($db->getCount()>0)
                                {
                                    $photo_arr=$db->getArray();
                                    echo "<div class='f-l menu-foto photo gal' data-img='".$photo_arr[0]['name']."_".$photo_arr[0]['id'].".jpg' data-folder='../img/menu/'></div>";
                                }
                                else
                                {
                                    echo '<div class="f-l menu-foto"></div>';
                                }
                                echo '<div class="f-l menu-f"><div class="menu-name">'.$arr_sub_sub_val['name'].'</div>';
                                if(!empty($arr_sub_sub_val['description']))
                                {
                                    echo '<div class="menu-descr">'.$arr_sub_sub_val['description'].'</div>';
                                }
                                echo '</div>';
                                echo '<div class="f-r menu-fi">';
                                    echo ($arr_sub_sub_val['delivery']==1)?'<div class="del"></div>':'<div class="del back-none"></div>';
                                echo '</div>';

                                echo '<div class="f-r menu-fo menu-name">';
                                    echo '<input type="hidden" name="pr" value="'.$arr_sub_sub_val['price'].'"><input type="hidden" name="id" value="'.$arr_sub_sub_val['id'].'"><div class="f-l menu-minus"></div><input class="f-l menu-col menu-name" readonly="" value="0"><div class="f-l menu-plus"></div>';
                                echo '</div>';

                                echo '<div class="f-r menu-t menu-name">'.$arr_sub_sub_val['price'].'</div>';
                                echo '<div class="f-r menu-s menu-name">'.$arr_sub_sub_val['weight'].'</div>';
                                echo '<div class="cl"></div>';
                                echo '</li>';
                            }
                           echo "</ul>";
                        }
                        if($count>0)
                        {
                            echo "</li>";
                        }

                    }

                }
               else echo "<ul>";
                $q_sub_ ="SELECT * FROM menu_m WHERE  parent = '$arr_main_val[id]' AND name<>'' AND element_submenu = 0 AND invisible=0 AND price<>'' AND weight<>'' ORDER BY name";
				$db->query($q_sub_);
                if($db->getCount()>0)
                {
                    $arr_prosto_bludo=$db->getArray();
                    foreach($arr_prosto_bludo as $arr_prosto_bludo_index=>$arr_prosto_bludo_val)
                    {
                        echo '<li style="padding: 16px 10px 10px 10px;margin-left:21px;" class="bludo">';
                        $sqlphoto='SELECT * FROM menuphoto WHERE parent='.$arr_prosto_bludo_val['id'].' AND temp=1 ORDER BY dtcreate DESC LIMIT 1';
                        $db->query($sqlphoto);
                        if($db->getCount()>0)
                        {
                            $photo_arr=$db->getArray();
                            echo "<div class='f-l menu-foto photo gal' data-img='".$photo_arr[0]['name']."_".$photo_arr[0]['id'].".jpg' data-folder='../img/menu/'></div>";
                        }
                        else
                        {
                            echo '<div class="f-l menu-foto"></div>';
                        }
                        echo '<div class="f-l menu-f"><div class="menu-name">'.$arr_prosto_bludo_val['name'].'</div>';
                        if(!empty($arr_prosto_bludo_val['description']))
                        {
                            echo '<div class="menu-descr">'.$arr_prosto_bludo_val['description'].'</div>';
                        }
                        echo '</div>';
                        echo '<div class="f-r menu-fi">';
                            echo ($arr_prosto_bludo_val['delivery']==1)?'<div class="del"></div>':'<div class="del back-none"></div>';
                        echo '</div>';

                        echo '<div class="f-r menu-fo menu-name">';
                            echo '<input type="hidden" name="pr" value="'.$arr_prosto_bludo_val['price'].'"><input type="hidden" name="id" value="'.$arr_prosto_bludo_val['id'].'"><div class="f-l menu-minus"></div><input class="f-l menu-col menu-name" readonly="" value="0"><div class="f-l menu-plus"></div>';
                        echo '</div>';

                        echo '<div class="f-r menu-t menu-name">'.$arr_prosto_bludo_val['price'].'</div>';
                        echo '<div class="f-r menu-s menu-name">'.$arr_prosto_bludo_val['weight'].'</div>';
                        echo '<div class="cl"></div>';
                        echo '</li>';
                    }
                }
                 echo "</ul>";
                 echo '</li>';
          }
          echo '<div class="menu-delim"></div>';
    }

    echo "</form>";
    ?>
    </div>
    <div class="cl"></div>


        <div class="menu-price-on f-l">Цены в грн. на <?php
            $sql="SELECT date FROM actual_date_price";
            $db->query($sql);
            if($db->getCount()>0)
            {
                $date=$db->getValue();
                $date=explode('-',$date);
                echo $date[2].".".$date[1].".".$date[0];
            }
            ?></div>
    <div class="f-r">
        <div class="menu-price-on bigger f-r"><div class="total">Итого: 0грн</div><div class="price-for-delivery summ_zakaz">Сумма заказа для доставки: 0грн</div></div>
    </div>
    <div class="cl"></div>
        <div class="f-l menu-price-on price-on-phone" style="margin-top: -29px;line-height: 25px;">
            * Цены можно уточнить по телефону (095) 172-72-72<br />или у официанта в заведении
        </div>
    <div class="f-r free-delivery">Бесплатная доставка осуществляется свыше 250грн</div>
     <div class="cl"></div>
     
    
    </div>
</div>
 <div class="cl"></div>
     <!--div style="width: 100%; display: none;" class="scrollmenu">
        <div style="position:fixed;width: 100%;bottom: 0px;left: 0px;height: 45px;background: #4d4135 url('../img/back.jpg') repeat;border-top: 1px solid #7b6b3d;">
            <div style="position: relative;max-width: 1350px;margin: 0 auto;border-top: 1px solid #7b6b3d;">
                <div style="margin:8px 59px;">
                    <div >
                        <div class="f-l ">
                                <a href="/rus/restaurant#oform"><div class="swim f-l icons-menu-zakaz swim-oformit">
                                    <div class="f-l swim-zakaz"></div>
                                    <div class="f-l swim-text">Оформить заказ</div>
                                </div></a>
                                 <div class="swim f-l icons-menu-print" style="margin:0 0 0 43px;">
                                    <a class='swimprint' href="#"><div class="f-l swim-print"></div>
                                    <div class="f-l swim-text">Печать выбранных позиций</div></a>
                                </div>
                                
                        </div>
                        <div class="f-r ">
                            <div class="swim-itogo-text f-l">Итого: 0 грн</div><div class="f-l">&nbsp;&nbsp;</div>
                            <div class="swim-itogo-text-deliv f-l">Сумма заказа для доставки: 0 грн</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div-->
 <div class="cl"></div>
 <div class='icons-menu'>
    <div class="f-l icons-menu-zakaz">
             <div class="f-l ic_zakaz"></div><div class="f-l menu-icoons-text">Оформить заказ</div>
    </div>
    <div class="f-l icons-menu-print">
            <div class="f-l ic_print"></div><div class="f-l menu-icoons-text">Печать выбранных позиций</div>
    </div>
    <div class="f-l icons-menu-mail">
            <div class="f-l ic_mail"></div><div class="f-l menu-icoons-text">Отправить выбранные позиции на почту</div>
    </div>
     <div class="cl"></div>
 </div>
 <div class="cl"></div>

 <div class="p-r"><div class="p-a" style="top:-50px;"> <a name="oform">&nbsp;</a></div></div>

<div class='oform page_restarea' style="display:none; background: #ffffff;padding: 30px 20px;margin-top: 40px; ">

    <div class="doc-el">
        <div class="m-b">
            <form method="post">
                <div class="f_l left_block" style="width: 22%;margin-right: 2%;">
                    <p>Оформить заказ</p>

                    <span>Мы осуществляем доставку в Ворошиловский, Калиникский, Ленинский и Куйбышевский районы с 11.00 до 23.00</span>
                    <span>Заказ  от 250,00  грн.- доставка бесплатная</span>
                    <span>Заказ до 250,00 грн. – оплата услуг такси в обе стороны</span>

                </div>
                <input type="hidden" name="h_price"/>
                <input type="hidden" name="h_delivery_price"/>
                <div class='f-r right_block' style="width: 33%;">
                    <div class="cl"></div>
                <div class="disabled">
                    <div class="oform-input-text" style="font-size: 16px">Адрес доставки</div>
                    <textarea name='address' disabled="disabled" class="input_oform" style="width:372px"></textarea>
                </div>
                    <div class="oform-after-input" ></div>
                    <div class="cl"></div>
                    <div class="cl"></div>
                    <div class="oform-after-input" ></div>
                    <div class="oform-input-text" style="font-size: 16px;margin-top: -2px;">Комментарий</div>
                    <textarea name='comm' class="input_oform" style="width:372px"></textarea>
                    <div class="cl"></div>
                    <div class="f-l bron-itogo" style="text-align: right;overflow: hidden;width: 100%;margin: 15px 0 2px 0;">
                        <span class="text">Итого: <span class="oform-block-all-price">0</span> грн</span><br/>
                        <span class="text summ_zakaz">Сумма заказа для доставки: <span class="oform-block-deliv-price">0</span> грн</span>
                    </div>

                    <input type='submit' class='button bron-sub big_bt' value='Оформить заказ'/>
                </div>
                <div   style="width: 41%;overflow: hidden;">

                    <div class="" >

                        <div class="oform-input-text">Место проведения *</div>

                        <input type="radio" id="rest" checked name="rest" style="margin: -4px 3px 0 0;">
                        <label for="rest" style="display: inline-block;margin: 10px 51px 10px 0;">Ресторан</label>

                        <input type="radio" id="deliv" name="deliv" style="margin: -4px 3px 0 0;">
                        <label for="deliv"> Доставка</label>
                    </div>
                    <div class="" >
                        <div class="oform-input-text">Дата/время проведения</div>
                        <input class="input_oform w_100" type="text" name="data">
                    </div>
                    <div class="" >
                        <div class="oform-input-text">Имя/организация *</div>
                        <input class="input_oform w_100" name="name" type="text">
                    </div>
                    <div class="" >
                        <div class="oform-input-text">Событие</div>
                        <input class="input_oform w_100" name="event" type="text">
                    </div>
                    <div class="cl"></div>
                    <div class="f-l number" >
                        <div class="oform-input-text">Контактный телефон *  </div>
                        <input class="input_oform r_o" type="text" name="phonecode" value="">
                        <input class="input_oform" name="phone" type="text" style="width: 56%;">
                        <div class="clr"></div>
                        <span class="text_gray">*Номер телефона в международном формате (+380 95 123 22 33)</span>
                    </div>

                    <div class="f-r" style="width: 42%;margin-right: 11px;text-align: right;">
                        <div class="oform-input-text">  Количество человек </div>
                        <input class="input_oform" name="col" type="text" style="width: 125px;">
                    </div>
                    <div class="oform-after-input"></div>
                    <div class="cl"></div>

                </div>

            </form>

        </div>
    </div>
    <div class="clr"></div>
</div>
    </div>
</div>

  <div class="cl"></div>

