<?php 
    $page->addScript('js/exaptionm.js','js/jquery.panorama.js','js/jquery.restbron.js','js/jquery.form.js','js/jquery.mousewheel.min.js','js/jquery-ui_1.9.1.js','js/date.js','js/jquery.panoramaelse.js');
    $page->addCss('css/jquery-ui-1.9.1.css');
    
?>
<script type="text/javascript">

    jQuery(document).ready(function() {
        jQuery('#mycarousel').jcarousel({
            /* wrap: 'circular',*/
            visible: 5,
            scroll: 2
        });
    });

</script>
<div class="m-b ">
<div class="mar_40">
 <div class="cl"></div>
 <div class="af-header"></div>
  <h1 class="title" style="margin-bottom: 14px;">Турецкий Хамам</h1>

        <div class="rest-lu-block-pan-cont" style="height: 380px">

            <div class="panorama">

                <div id="fo-map" class="border_gray">
                    <div class="panorama-view">
                        <div class="panorama-container">
                            <img src="../img/pan/hamam_new.jpg" data-width="2453" data-height="380" data-timeout="100" class="preload position_absolute left_zero" alt="" />
                        </div>
                    </div>
                </div>

                <div class="p-r" style="width: 100%;margin-top:-34px;">
                    <div style="background: url('../img/panoram_line.png') no-repeat;width:529px;margin:0 auto;height:9px;"></div>
                    <div style="width:529px;margin:0 auto;">
                        <div class="pandelim p-r" style="left:0;"></div>

                    </div>
                    <div class='panline p-r width-h-p' style="margin:0 auto;height:35px;top:-54px;">
                        <div style="width:529px;margin:0 auto;height:100%"></div>
                    </div>
                </div>
            </div>

        </div>


    <div class="cl"></div>
    <div class="menu-container page_restarea">
        <div class="menu-inside-container">
           <p>Хамам – источник истинного наслаждения, место, где царит расслабляющая тело и душу атмосфера. Процедура несет в себе оздоровление, омоложение тела и снимает накопившуюся усталость.</p>
            <p>Если Вы решили устроить себе день красоты, то лучше турецкого хамама не придумаешь. Вы не почувствуете изнуряющего жара, а организм будет готов к восприятию любого косметического ухода. Увлажненные волосы, сияющая кожа, отдохнувшее, а главное помолодевшее тело – это залог успеха современной женщины. Мужчина же сможет почувствовать себя настоящим султаном.</p>
            <p>Хотите узнать, что такое настоящий турецкий хамам? Приходите в Люфари.</p>
        </div>
    </div>


    <div style="position: relative;margin-top: 15px;">
            <div class='width-h-p' >


                <ul id="mycarousel" class="jcarousel-skin-tango menu-gal-restarea width-h-p" >
                    <li>
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/01.jpg'/>
                    </li>
                    <li>
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/02.jpg'/>
                    </li>
                    <li class='margin-zero'>
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/03.jpg'/>
                    </li>
                    <li >
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/04.jpg'/>
                    </li>
                    <li>
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/05.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/06.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="6" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/07.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="7" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/08.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="8" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/09.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="9" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/10.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="10" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/11.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="11" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/12.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="12" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/13.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="13" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/14.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="14" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/15.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="15" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/16.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="16" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/17.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="17" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/18.jpg'/>
                    </li>
                    <li class="margin-zero">
                        <img alt="" class='gal width-h-p' data-ajax="true" data-current="18" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/19.jpg'/>
                    </li>
                </ul>




            <!--ul class="menu-gal-restarea width-h-p">
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/1.jpg'/>
                </li>
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/2.jpg'/>
                </li>
                <li class='margin-zero'>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/3.jpg'/>
                </li>
                <li >
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/4.jpg'/>
                </li>
                <li>
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/5.jpg'/>
                </li>
                <li class="margin-zero">
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/6.jpg'/>
                </li>
            </ul-->

            </div>
            <div class="cl"></div>
            <!--div class="rest-t" >Панорама 360&deg;</div>

			<div class="width-h-p p-r ">
							<div class="p-a gallery-ugol-left-top"></div>
                            <div class="p-a gallery-ugol-right-top"></div>
                            <div class="p-a gallery-ugol-left-buttom"></div>
                            <div class="p-a gallery-ugol-right-buttom"></div>
			<div class="areappan">
			<img alt="" data-swf="hamam.jpg" data-width="1530~1920~2400" data-height="459~576~720" data-360="1" class='virt width-h-p' src="/../img/photos/area/pan/hamam.jpg"/></div>
    </div--></div>
     <div class="cl"></div>


    <!-- -->




    <!-- -->

             <?
             $arr=$DLL->getServicesByType(2);
             if(count($arr)>0)
             {
                 echo ' <div class="title_text_restarea" style="margin-bottom: 34px;margin-top: 31px;"><span class="rest_title_left"></span>Перечень услуг<span class="rest_title_right"></span></div>
                         <div class="cl"></div>

                         <div class="menu-container p-r">
                             <div class="menu-inside-container" style="padding: 45px 40px;">
                                 <div class="width-h-p">';
                 echo '<ul class="width-h-p rest-area-uslugi">';
                 foreach($arr as $arr_i=>$arr_v)
                 {
                     if($arr_i==0)
                     {
                         echo '<li class="top-zero">';
                     }
                     else
                     {
                         echo '<li>';
                     }
                     echo '<div class="rest-area-uslugi-name f-l">'.$arr_v['name'].'</div>
                                <div class="rest-area-uslugi-desc f-l">'.$arr_v['description'].'</div>
                                <div class="rest-area-uslugi-price f-l">'.$arr_v['price'].' грн.</div>
                            </li>';
                     if(($arr_i+1)%1==0 )
                     {
                         echo '<li class="cl"></li>';
                     }
                 }
                 echo '</ul>';
                 echo '       <div class="cl"></div>
                             </div>
                         </div>
                     </div>';
             }
             ?>




 <div class='oform page_restarea hamam' style="display:block;height:auto; background: #ffffff;padding: 30px 20px;margin-top: 40px; ">

     <div class="doc-el">
         <div class="m-b">
             <?
             $form="hamam";
            include "lib/bathhamammini.php";
             ?>

         </div>
     </div>
     <div class="clr"></div>
 </div>

 </div>
 </div>

  <div class="cl"></div>
     <div class="doc-el">
             <div class="m-b">

            </div>
     </div>
<script type="text/javascript">
    function restareaphotos()
    {
        var w=('innerWidth' in window) ? window.innerWidth : document.body.offsetWidth;
        /*if(w>=1280)
        {
            $('.menu-gal-restarea li').each(function(i)
            {
                if(i!=0 && (i+1)%3==0)
                {
                    $(this).addClass('margin-zero').removeClass('little')
                }
            })
        }
        else
        {
            $('.menu-gal-restarea li').removeClass('margin-zero').addClass('little')
        }*/
        if(w<=1000)
        {
            $('.top-rest-area').addClass('small')
            $('.top-rest-area .ic_hamam,.top-rest-area .ic_bany,.top-rest-area .ic_zal').addClass('small')
        }
        else
        {
            $('.top-rest-area').removeClass('small')
            $('.top-rest-area .ic_hamam,.top-rest-area .ic_bany,.top-rest-area .ic_zal').removeClass('small')
        }
    }
    $(function()
    {
        restareaphotos()
    })
    $(window).resize(function()
    {
        restareaphotos()
    })
</script>