<?php 
    $page->addScript('js/exaptionm.js','js/jquery.panorama.js','js/jquery.restbron.js','js/jquery.form.js','js/jquery.mousewheel.min.js','js/jquery-ui_1.9.1.js','js/date.js','js/jquery.panoramaelse.js');
    $page->addCss('css/jquery-ui-1.9.1.css');
    
?>
<div class="m-b">
 <div class="cl"></div>
 <div class="af-header"></div>
    <div class="f-l"><h1>Зона отдыха «Люфари»</h1></div>
   
    <div class="f-r top-rest-area">
        <a href="/rus/rest/area#hamam">
        <div class="f-l icons-menu-hamam">
                 <div class="f-l menu-icoons-text-top margin-zero">Хамам</div><div class="f-l ic_menu ic_hamam"></div>
        </div></a>
          <a href="/rus/rest/area#bany"><div class="f-l icons-menu-bany">
                 <div class="f-l menu-icoons-text-top margin-zero">Баня</div><div class="f-l ic_menu ic_bany"></div>
        </div></a>
          <a href="/rus/rest/area#mini-zal"><div class="f-l icons-menu-zal">
                 <div class="f-l menu-icoons-text-top margin-zero">Мини-банкетный зал</div><div class="f-l ic_menu ic_zal"></div>
        </div></a>
    </div>
    <div class="cl"></div>
    <div class="mezhblocs"></div>
    <div class="rest-t">Зона отдыха в «Люфари» это особое место. Здесь господствует<br />покой и замирает время.</div>
    <div class="cl"></div>
    <div class="mezhblocs"></div>
    <div class="f-l" style="width:47%">
            <div class="transfer-t font-style-normal margin-zero">
               Для восстановления жизненных сил, проведения различных праздников и неформальных встреч «Люфари» предлагает своим гостям посетить выдержанные в лучших традициях и созданные по всем правилам: «Баню на дровах» с бассейном и «Травяным водопадом», «Турецкий Хамам» с джакузи, а также мини-банкетный зал с бильярдом.
            </div>
    </div>
    <div class="f-r" style='width:48%;'>
            <div class="transfer-t font-style-normal margin-zero">
                Для Хамам и бани на дровах у нас предусмотрена возможность отдельного входа с соблюдением столь важной конфиденциальности, что позволит вам почувствовать себя максимально комфортно и полноценно насладиться отдыхом.
            </div>
    </div>
    <div class="cl"></div>
    <div class="mezhblocs-rest-area"></div>
    <div class="cl"></div>
    <div class="p-r"><div class="p-a" style="top:-50px;"> <a name="hamam">&nbsp;</a></div></div>
    <div class="rest-t-sub-title font-style-italic margin-zero">Турецкий Хамам</div>
    <div class="f-l" style="width:47%">
            <div class="hamam-ic-m-t transfer-t f-l font-style-normal margin-zero">
                <div class=" hamam-ic f-l"></div>Турецкая баня хамам - это особенная философия<br />отдыха для тела и души.
            </div>
            <div class="cl"></div>
                <div class="f-l" style="width:72%;">
                    <div class="transfer-t font-style-normal">
                        Отличительной чертой хамам является то, что при невысокой температуре (30&deg; - 50&deg;) в мраморной комнате поддерживается достаточно высокая влажность. Благодаря данной особенности весь организм наполняется положительной энергетикой и живительной влагой. 
                    </div>
                </div>
                 <div class="f-r" style="width:27%;margin-top: 50px;">
                    <img alt="" class="width-h-p" src="../img/restareapods.png"/>
                </div>
                
            <div class="cl"></div>
                <div class="f-l" style="width:25.5%;margin-top: 50px;">
                    <img alt="" class="width-h-p" src="../img/restareadum.png"/>
                </div>
                <div class="f-r" style="width:72%;">
                    <div class="transfer-t font-style-normal">
                       <p>Традиционная процедура, присущая хамам - это мыльный массаж, который начинается с активного пилинга и заканчивается в облаке мыльной пены, насыщая организм жизненной энергией и неповторимым чувством блаженства.</p><br />Помимо сауны, вас также ожидает бодрящий гидромассаж в джакузи.
                       <br />
                       
                    </div>
                </div>
                <div class="cl"></div>
                <!--<div class="button predv-bron bron king text-align-c"> <a href="rus/hotel#reservation">Предварительное бронирование</a></div>-->
                
    </div>
    <div class="f-r" style='width:48%;'>
            <div class='width-h-p'>
            <div class="rest-t" >Фотографии</div> 
            <ul class="menu-gal-restarea width-h-p">
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/1.jpg'/>
                </li>
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/2.jpg'/>
                </li>
                <li class='margin-zero'>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/3.jpg'/>
                </li>
                <li >
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/4.jpg'/>
                </li>
                <li>
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/5.jpg'/>
                </li>
                <li class="margin-zero">
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/hamam/" src='../img/photos/area/hamam/6.jpg'/>
                </li>
            </ul>
            
            </div>
            <div class="cl"></div>
            <div class="rest-t" >Панорама 360&deg;</div>
            
			<div class="width-h-p p-r ">
							<div class="p-a gallery-ugol-left-top"></div>
                            <div class="p-a gallery-ugol-right-top"></div>
                            <div class="p-a gallery-ugol-left-buttom"></div>
                            <div class="p-a gallery-ugol-right-buttom"></div>
			<div class="areappan">
			<img alt="" data-swf="hamam.jpg" data-width="1530~1920~2400" data-height="459~576~720" data-360="1" class='virt width-h-p' src="/../img/photos/area/pan/hamam.jpg"/></div>
    </div></div>
     <div class="cl"></div>
    <div class="mezhblocs-rest-area"></div>
    
    <!-- -->
    
    <div class="p-r"><div class="p-a" style="top:-50px;"> <a name="bany">&nbsp;</a></div></div>
    
    <div class="rest-t-sub-title font-style-italic margin-zero">Баня на дровах</div>
    <div class="f-l" style="width:47%">
            <div class="bany-ic-m-t transfer-t f-l font-style-normal margin-zero " style="width:75%;">
                <div class=" bany-ic f-l"></div>Уже на протяжении нескольких веков баня на дровах является одним из любимых мест отдыха человека. Русская баня - прекрасная терапевтическая процедура, одинаково полезная, как для души, так и для тела. Особенно баня полезна тем, кто  много уделяет времени офисной работе, так как хорошо восполняется недостаток движения, происходит комплексная отчистка организма и повышается иммунитет.
            </div>
             <div class="f-r" style="width:25%;margin-top: 50px;">
                    <img alt="" class="width-h-p" src="../img/venik.png"/>
             </div>
                
            <div class="cl"></div>
            
            <div class="f-l" style="width:25.4%;margin-top: 50px;">
                <img alt="" class="width-h-p" src="../img/vedro.png"/>
            </div>
            <div class="f-r" style="width:72%;">
                <div class="transfer-t font-style-normal">
                   <p>Одной из приятных процедур нашей бани на дровах является травяной водопад. Любители острых ощущений и закаливания по достоинству оценят незабываемые впечатления от контрастного обливания холодной водой после выхода из парилки в лучших традициях русской бани. Также к вашим услугам предоставлен бассейн.</p>
                   
                </div>
            </div>
            <div class="cl"></div>
            <div class="transfer-t font-style-normal width-h-p">
                Все необходимые аксессуары для посещения бани на дровах и хамам уже включены в стоимость заказа. В качестве дополнительных услуг мы рады вам предложить сеансы расслабляющего массажа в уютных, оборудованных профессионально, массажных кабинетах, а также различные блюда и напитки, выбранные вами в <a href="/rus/restaurant#menu">меню ресторана «Люфари»</a>
            </div>
                <!--<div class="button predv-bron bron king text-align-c"> <a href="rus/hotel#reservation">Предварительное бронирование</a></div>-->
                
    </div>
    <div class="f-r" style='width:48%;'>
            <div class='width-h-p'>
            <div class="rest-t" >Фотографии</div> 
            <ul class="menu-gal-restarea width-h-p">
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/1.jpg'/>
                </li>
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/2.jpg'/>
                </li>
                <li class="margin-zero">
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/3.jpg'/>
                </li>
                <li >
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/4.jpg'/>
                </li>
                <li>
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/5.jpg'/>
                </li>
                <li class="margin-zero">
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/6.jpg'/>
                </li>
            </ul>
            
            </div>
            <div class="cl"></div>
            <div class="rest-t" >Панорама 180&deg;</div>
			<div class="width-h-p p-r ">
							<div class="p-a gallery-ugol-left-top"></div>
                            <div class="p-a gallery-ugol-right-top"></div>
                            <div class="p-a gallery-ugol-left-buttom"></div>
                            <div class="p-a gallery-ugol-right-buttom"></div>
            <div class="areappan">
			<img alt="" data-swf="bany.jpg" data-width="1275~1600~2000" data-height="459~576~720" data-360="0" class='virt width-h-p' src="/../img/photos/area/pan/bany.jpg"/></div>
            </div>
			<div class="transfer-t font-style-normal">После СПА-процедур, всех гостей ожидает комната отдыха, где сидя на мягких диванах, дамы могут насладиться приятными ощущениями за чашечкой ароматного целебного чая, а джентльмены, набравшись сил и энергии, сыграть партию в русский бильярд.</div>
    </div>
     <div class="cl"></div>
    
    <!-- -->
    <div class="cl"></div>
    <div class="mezhblocs-rest-area"></div>
     <!-- -->
     
     
    <div class="p-r"><div class="p-a" style="top:-50px;"> <a name="mini-zal">&nbsp;</a></div></div>
    <div class="rest-t-sub-title font-style-italic margin-zero">Мини - банкетный зал</div>
    <div class="f-l" style="width:48%">
            <div class="zal-ic-m-t transfer-t f-l font-style-normal margin-zero " style="width:73%;">
                <div class="zal-ic f-l"></div>После посещения бани или хамам вы можете отдохнуть в уютном небольшом зале с возможностью сыграть в русский бильярд, посмотреть хороший фильм, а также весело провести время в компании друзей.
            </div>
             <div class="f-r" style="width:27%;margin-top: 50px;">
                    <img alt="" class="width-h-p" src="../img/bilyard.png"/>
             </div>
                
            <div class="cl"></div>
            
            <div class="f-l" style="width:25.2%;margin-top: 15px;">
                <img alt="" class="width-h-p" src="../img/bilyard2.png"/>
            </div>
            <div class="f-r" style="width:72%;">
                <div class="transfer-t font-style-normal">
                   Арендовать мини - банкетный зал можно как вместе с одной из бань (турецкой либо русской), так и отдельно.
                </div>
            </div>
            <div class="cl"></div>
                <!--<div class="button predv-bron bron king text-align-c"> <a href="rus/hotel#reservation">Предварительное бронирование</a></div>-->
                
    </div>
    <div class="f-r" style='width:48%;'>
            <div class='width-h-p'>
            <div class="rest-t" >Фотографии</div> 
            <ul class="menu-gal-restarea width-h-p">
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/mini-zal/" src='../img/photos/area/mini-zal/1.jpg'/>
                </li>
                 <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/mini-zal/" src='../img/photos/area/mini-zal/2.jpg'/>
                </li>
                <li class="margin-zero">
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/mini-zal/" src='../img/photos/area/mini-zal/3.jpg'/>
                </li>
                <li >
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/mini-zal/" src='../img/photos/area/mini-zal/4.jpg'/>
                </li>
                <li>
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/mini-zal/" src='../img/photos/area/mini-zal/5.jpg'/>
                </li>
                <li class="margin-zero">
                     <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/mini-zal/" src='../img/photos/area/mini-zal/6.jpg'/>
                </li>
            </ul>
            
            </div>
            <div class="cl"></div>
     </div>
     <div class="cl"></div>
    <div class="mezhblocs-rest-area"></div>
    <div class="rest-t-sub-title font-style-italic margin-zero">Бронирование и оплата:</div>
    <div class="f-l" style="width:47%">
            <div class="transfer-t font-style-normal">
               Стоимость аренды часа в бане на дровах или турецком хамаме составляет 200,00 грн/час на первого человека +50,00 грн/час на каждого следующего гостя. Минимальное время аренды - 2 часа. В стоимость входят все необходимые аксессуары для приятного время проведения в бане или хамаме: полотенца, халаты, тапочки, веники.
            </div>
    </div>
    <div class="f-r" style="width:48%;">
            <div class="transfer-t font-style-normal">
                <p>Вы также можете заказать дополнительные услуги, аксессуары и порадовать себя изысканной кухней <a href="/rus/restaurant#menu">ресторана «Люфари»</a>.</p>
                <br />
                Стоимость аренды мини - банкетного зала с бильярдом - 150,00 грн/час.
            </div>
    </div>
    <!-- -->
    <div class="cl"></div>
    <div class="mezhblocs"></div>
    <!--<div class="p-r"><div class="p-a" style="top:-50px;"> <a name="reservation">&nbsp;</a></div></div>
    <div class="rest-t-sub-title font-style-italic margin-zero bron">Предварительная бронь</div>-->
 </div>
 </div>
 
 <!--<div class='oform' style="display:block;height:362px;">
        <div class='oform-sh-top p-a'></div>
        <div class='oform-sh-bottom p-a'></div>
        <div class="doc-el">
            <div class="m-b">
                <div class="oform-form-w">
                    <form method="post">
                        <div class='f-l' style="width:415px;">
                            
                            <div class="f-l">
                                 <div class="oform-input-text">Дата вьезда</div>
                                 <div class="p-r f-l"><input name='data' class='date f-l' readonly style='width: 175px' value="<?php echo date('d.m.Y');?>"/><div class="delete p-a" title="Удалить дату"></div></div><div class="f-l calend"></div>
                            </div>
                            <div class="f-r">
                                 <div class="oform-input-text">Время вьезда</div>
                                 <div><div class="selecth f-l">
                                                <select name="hour"><option value="00"> </option>
                                                          <option value="01">1</option>
                                                          <option value="02">2</option>
                                                          <option value="03">3</option>
                                                          <option value="04">4</option>
                                                          <option value="05">5</option>
                                                          <option value="06">6</option>
                                                          <option value="07">7</option>
                                                          <option value="08">8</option>
                                                          <option value="09">9</option>
                                                          <option value="10">10</option>
                                                          <option value="11">11</option>
                                                          <option value="12">12</option>
                                                          <option value="13">13</option>
                                                          <option value="14">14</option>
                                                          <option value="15">15</option>
                                                          <option value="16">16</option>
                                                          <option value="17">17</option>
                                                          <option value="18">18</option>
                                                          <option value="19">19</option>
                                                          <option value="20">20</option>
                                                          <option value="21">21</option>
                                                          <option value="22">22</option>
                                                          <option value="23">23</option>
                                                          <option value="00">00</option>
                                       </select>
                                       
                                       </div>
                                       
                                       <div class='f-l oform-input-text' style="text-align:center;width: 20px;line-height: 21px;">:</div><div class="selecth f-r"><select class='selecth' name="min"><option value="00"> </option>
                                                          <option value="15">15</option>
                                                          <option value="30">30</option>
                                                          <option value="45">45</option>
                                                          <option value="00">00</option>
                                       </select></div></div>
                            </div>
                            <div class="cl"></div>
                            <div class="oform-after-input"></div>
                            <div class="cl"></div>
                                <div class="f-l" style="width: 395px;">
                                    <div class="f-l" style="width:45%;">
                                        <div class="oform-input-text">Количество часов</div>
                                        <input name="days" class="width-h-p" value="1"/>
                                    </div>
                                    <div class="f-r" style="width:40%;">
                                        <div class="oform-input-text">Количество&nbsp;человек</div>
                                        <input name="col" class="width-h-p" value="1"/>
                                    </div>
                                </div>
                            
                             <div class="cl"></div>
                             <div class="oform-after-input"></div>
                             <div class="hotel-type-room f-l">
                                 <div class="oform-input-text">Помещения</div>
                                 <div class="f-l">
                                    <div class="rest-area">
                                    <div class="rest-area-top">
                                        <div class="rest-area-div-bany">
                                            <div class="rest-area-bany"></div>
                                        </div>
                                        <div class=" rest-area-div-zal">
                                           <div class="rest-area-zal"></div>
                                        </div>
                                        <div class="rest-area-div-hamam">
                                             <div class="rest-area-hamam"></div>
                                        </div>
                                    </div>
                                        
                                    </div>
                                 </div>
                                 <div class="f-r" style="margin-left: 10px;">
                                     <input class='f-l' style='margin: 8px 3px 0px 5px;' name="standart" checked="checked" type="radio" /> <div class="f-l oform-input-text">Баня</div>
                                     <div class="cl"></div>
                                     <input class='f-l' style='margin: 8px 3px 0px 5px;' name="king" type="radio" /><div class="f-l oform-input-text">Хамам</div>
                                     <div class="cl"></div>
                                     <input class='f-l' style='margin: 8px 3px 0px 5px;' name="king" type="radio" /><div class="f-l oform-input-text">Мини-банкетный зал</div>
                                 </div>
                            </div>
                            <div class="cl"></div>
                         </div>
                         <div class='f-r'>
                            <div class="oform-input-text">ФИО (как к вам обращаться)*</div>
                            <div><input name="name" style="width:372px" /></div>
                            <div class="cl"></div>
                            <div class="oform-after-input"></div>
                            <div class="cl"></div>
                            
                            <div class="oform-input-text">Ваш контактный номер телефона*</div>
                            <div><input name="phone" style="width:372px" value="+"/></div>
                            <div class="cl"></div>
                            <div class="oform-after-input" ></div>
                            <div class="oform-input-text">Комментарий</div>
                            <textarea name='comm' style="width:372px"></textarea>
                            <div class="cl"></div>
                            <div class="f-l bron-itogo" style="text-align:left;margin-top: 34px;overflow: hidden;">
                                <span class="text">Итого:</span> 800 грн
                            </div>
                            <div class="f-r" style="text-align: right;"><input type='submit' class='button bron-sub' value='Предварительный заказ'/></div>
                        </div>
                        </form>
                </div>
            </div>
        </div>
 </div>
 <div class="before-oform"></div>-->
  <div class="cl"></div>
 <div class="doc-el">
 <div class="m-b">
        <div class="rest-t-sub-title font-style-italic margin-zero">Перечень услуг:</div>
        <div class="menu-container p-r">
          <div class="p-a big-fugur-border-little-bottom"></div> 
          <div class="p-a big-fugur-border-little-top"></div> 
          <div class="p-a big-fugur-border-little-left"></div> 
          <div class="p-a big-fugur-border-little-right"></div> 
          
          <div class="p-a big-fugur-border-right-bottom"> </div> 
          <div class="p-a big-fugur-border-right-top"></div> 
          <div class="p-a big-fugur-border-left-bottom"></div> 
          <div class="p-a big-fugur-border-left-top"></div> 
          <div class="menu-inside-container">
          
          <div class="width-h-p">
                <ul class="width-h-p rest-area-uslugi">
                
                
                <?
                    $db->query("SELECT * FROM services WHERE invisible = 0 ORDER BY priority");
                    $count = $db->getCount();
                    if($count > 0){
                        $arr = $db->getArray();
                        
                        foreach($arr as $key=>$val){
                            echo ($key==0)?'<li class="top-zero">':'<li>';
                            echo '<div class="rest-area-uslugi-name f-l">'.$val['name'].'</div>';
                            echo '<div class="rest-area-uslugi-desc f-l">('.$val['description'].')</div>';
                            echo '<div class="rest-area-uslugi-price f-l">'.$val['price'].' грн.</div>';
                            echo '</li>';
                            echo '<li class="cl"></li>';
                        }
                    }
                ?>
                <!--li class="top-zero"> 
                <div class="rest-area-uslugi-name f-l">Мыльный массаж</div>
                <div class="rest-area-uslugi-desc f-l">(Начинается с активного пилинга и заканчивается в облаке мыльной пены, насыщая организм жизненной энергией и неповторимым чувством блаженства.)</div>
                <div class="rest-area-uslugi-price f-l">250 грн.</div>
                </li>
                <li class="cl"></li>
                <li> 
                <div class="rest-area-uslugi-name f-l">Расслабляющий массаж</div>
                <div class="rest-area-uslugi-desc f-l">(Заканчивается в облаке мыльной пены.)</div>
                <div class="rest-area-uslugi-price f-l">250 грн.</div>
                </li>
                <li class="cl"></li>
                <li> 
                <div class="rest-area-uslugi-name f-l">Мыльный массаж</div>
                <div class="rest-area-uslugi-desc f-l">(Начинается с активного пилинга и заканчивается в облаке мыльной пены, насыщая организм жизненной энергией и неповторимым чувством блаженства.)</div>
                <div class="rest-area-uslugi-price f-l">250 грн.</div>
                </li>
                <li class="cl"></li>
                <li> 
                <div class="rest-area-uslugi-name f-l">Ванна с шампанским</div>
                <div class="rest-area-uslugi-desc f-l">(Начинается с активного пилинга и заканчивается в облаке мыльной пены, насыщая организм жизненной энергией и неповторимым чувством блаженства. Облаке мыльной пены, насыщая организм жизненной энергией и неповторимым чувством блаженства.)</div>
                <div class="rest-area-uslugi-price f-l">250 грн.</div>
                </li>
                <li class="cl"></li>
                <li class="top-zero"> 
                <div class="rest-area-uslugi-name f-l">Обертывание морскими водоростями с пчелиным молоком</div>
                <div class="rest-area-uslugi-desc f-l">(Начинается с активного пилинга и заканчивается в облаке мыльной пены, насыщая организм жизненной энергией и неповторимым чувством блаженства.)</div>
                <div class="rest-area-uslugi-price f-l">250 грн.</div>
                </li-->
                </ul>
          <div class="cl"></div>
         </div>
</div>
</div>
</div>
<script type="text/javascript">
    function restareaphotos()
    {
        var w=('innerWidth' in window) ? window.innerWidth : document.body.offsetWidth;
        /*if(w>=1280)
        {
            $('.menu-gal-restarea li').each(function(i)
            {
                if(i!=0 && (i+1)%3==0)
                {
                    $(this).addClass('margin-zero').removeClass('little')
                }
            })
        }
        else
        {
            $('.menu-gal-restarea li').removeClass('margin-zero').addClass('little')
        }*/
        if(w<=1000)
        {
            $('.top-rest-area').addClass('small')
            $('.top-rest-area .ic_hamam,.top-rest-area .ic_bany,.top-rest-area .ic_zal').addClass('small')
        }
        else
        {
            $('.top-rest-area').removeClass('small')
            $('.top-rest-area .ic_hamam,.top-rest-area .ic_bany,.top-rest-area .ic_zal').removeClass('small')
        }
    }
    $(function()
    {
        restareaphotos()
    })
    $(window).resize(function()
    {
        restareaphotos()
    })
</script>