<?php
$page->addScript('js/exaptionm.js','js/jquery.panorama.js','js/jquery.restbron.js','js/jquery.form.js','js/jquery.mousewheel.min.js','js/jquery-ui_1.9.1.js','js/date.js','js/jquery.panoramaelse.js');
$page->addCss('css/jquery-ui-1.9.1.css');

?>
<script type="text/javascript">

    jQuery(document).ready(function() {
        jQuery('#mycarousel').jcarousel({
            /* wrap: 'circular',*/
            visible: 5,
            scroll: 2
        });
    });

</script>
<div class="m-b ">
<div class="mar_40 page_stock_more">
    <div class="mar_40 " style="margin: 0px 50px 0 50px !important;">
<div class="cl"></div>
<div class="af-header"></div>
<h1 class="title" style="margin-bottom: 11px;">дЛИННОЕ И НЕ СЛИШКОМ КОРОТКОЕ НАЗВАНИЕ СОБЫТИЯ</h1>
        <div class="clr"></div>
<div class="after_h1 f_l">с 3 мая 2013 г. 13:00 по 15 июня 2013 г. 20:00</div>
        <a href="/rus/stock" class="f_r button bron-sub back_bt" style="text-decoration:none !important;margin: 0;text-align: center;width: 128px !important;color: rgb(66, 55, 9);font-size: 22px;line-height: 43px;float: right;margin-top: -70px;margin-left: 20px;display: block;">Назад</a>
<div class="clr"></div>
    <div class="left">
        <div class="img">
            <img src="../img/stock/big.png" width="100%"/>
        </div>
        <div class="text">
            <p>Ресторан Люфари гостеприимно открывает свои двери ценителям отменной итальянской кухни и изысканных вин. Особая гордость ресторана - блюда всех регионов "Первого сада Европы", рецепты которых Шеф-повар привозит со всего мира, а также собственное производство моцареллы, пасты, лимончелло и вкуснейшей выпечки...Здесь Вы узнаете истинный характер национальной кухни и навсегда отдадите свое сердце Италии!</p>
            <p><i> В ресторане Люфари можно укрыться от посторонних глаз, полноценно отдохнуть, провести деловые переговоры или торжество.</i></p>
            <p> Легкая музыка, красивый интерьер, высокий уровень обслуживания и изысканные блюда от Шеф-повара делают любой вечер, проведенный в нем, незабываемымРесторан Люфари гостеприимно открывает свои двери ценителям отменной итальянской кухни и изысканных вин. Особая гордость ресторана - блюда всех регионов "Первого сада Европы", рецепты которых Шеф-повар привозит со всего мира, а также собственное производство моцареллы, пасты, лимончелло и вкуснейшей выпечки...Здесь Вы узнаете истинный характер национальной кухни и навсегда отдадите свое сердце Италии!</p>
            <p><i> В ресторане Люфари можно укрыться от посторонних глаз, полноценно отдохнуть, провести деловые переговоры или торжество.</i></p>
            <p> <a href="">Легкая музыкаa</a> красивый интерьер, высокий уровень обслуживания и изысканные блюда от Шеф-повара делают любой вечер, проведенный в нем, незабываемымРесторан Люфари гостеприимно открывает свои двери ценителям отменной итальянской кухни и изысканных вин. Особая гордость ресторана - блюда всех регионов "Первого сада Европы", рецепты которых Шеф-повар привозит со всего мира, а также собственное производство моцареллы, пасты, лимончелло и вкуснейшей выпечки...Здесь Вы узнаете истинный характер национальной кухни и навсегда отдадите свое сердце Италии!</p>

        </div>
    </div>
    <div class="right">
        <p style="font: 18px/23px arial;color: #ae8d40;margin-bottom: 10px;">Следующее событие</p>
        <div class="block_stock">

            <div class="img">
                <a href="/stock/more">
                    <div class="block_bg "><div class="bg"></div> <div class="center"></div> </div>
                    <img src="../img/stock/stock_1.png" width="100%"/>
                </a>
            </div>
            <div class="text">
                <div class="date_text">1с 3 мая 2013 г. 13:00 по 15 июня 2013 г.ло  20:00</div>
                <a href="">Длинное и не слишком короткое Название события</a>

            </div>
        </div>
        <p style="font: 18px/23px arial;color: #ae8d40;margin-bottom: 10px;">Предыдущее событие</p>
        <div class="block_stock">

            <div class="img">
                <a href="/stock/more">
                    <div class="block_bg "><div class="bg"></div> <div class="center"></div> </div>
                    <img src="../img/stock/stock_1.png" width="100%"/>
                </a>
            </div>
            <div class="text">
                <div class="date_text">1с 3 мая 2013 г. 13:00 по 15 июня 2013 г.ло  20:00</div>
                <a href="">Длинное и не слишком короткое Название события</a>

            </div>
        </div>
    </div>


<div class="cl"></div>




    </div>

    <div style="position: relative;margin-top: 35px;">
        <div class='width-h-p' >


            <ul id="mycarousel" class="jcarousel-skin-tango menu-gal-restarea width-h-p" >
                <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="0" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/01.jpg'/>
                </li>
                <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="1" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/02.jpg'/>
                </li>
                <li >
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="2" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/03.jpg'/>
                </li>
                <li >
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="3" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/04.jpg'/>
                </li>
                <li>
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="4" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/05.jpg'/>
                </li>
                <li >
                    <img alt="" class='gal width-h-p' data-ajax="true" data-current="5" data-folder="img/photos/area/bany/" src='../img/photos/area/bany/06.jpg'/>
                </li>
            </ul>

        </div>
    </div>
</div>
</div>

<script>
    $(document).on('mouseenter','.block_stock .img',function(){
        $(this).find('.block_bg').stop().fadeIn(200)
    }).on('mouseleave','.block_stock .img',function(){
            $(this).find('.block_bg').stop().fadeOut(200)
        })



</script>