<?php 
    $page->addScript('http://maps.google.com/maps/api/js?sensor=false');
?>
<div class="m-b">
 <div class="cl"></div>
 <div class="af-header"></div>
    <h>
    Контактная информация
    </h>
    <div class="cl"></div>
    <ul class="c-blocks">
        <li class="f">
            <div class="c-blocks-t">Адрес:</div>
            <div class='c-blocks-a'>
                <div>Украина, Донецк,</div><div>ул. Калинина, 118</div><div>(ориентир ТЦ "Империя мебели")</div>
            </div>
        </li>
        <li class="s">
            <div class="c-blocks-t">Телефоны:</div>
             <div class='c-blocks-a'>
                <div>(062) 304 63 53</div><div>(050) 304 95 82</div>
            </div>
        </li>
        <li class="t">
            <div class="c-blocks-t">E-mail:</div>
             <div class='c-blocks-a'>
                <div>reception@lyufari.com</div><div>head@lyufari.com</div>
            </div>
        </li>
        <li class="fo">
            <div class="c-blocks-t">Время работы:</div>
             <div class='c-blocks-a'>
                <div>Гостиница: круглосуточно</div>
                <div>Ресторан&nbsp;и&nbsp;доставка с&nbsp;10:00&nbsp;до&nbsp;23:00</div><div>Зона отдыха: круглосуточно</div>
            </div>
        </li>
    </ul>
    <div class="cl"></div>
    <div style="width: 100%;height:532px;margin-top:32px;" class="p-r">
        
        <div id="map" style="width: 100%;height:532px;margin-top:32px;">
      
         </div>
          <div class="map-r-b p-a" style="bottom: 0;right:0;"></div>  
          <div class="map-r-t p-a" style="top: 0;right:0;"></div> 
          <div class="map-l-b p-a" style="bottom: 0;"></div>  
          <div class="map-l-t p-a" style="top: 0;"></div> 
    </div>
    <div class="cl"></div>
    <div class="af-map"></div>
    <div class="f-l">
         <div class="trans-t">К нам можно доехать по г. Донецк<br />следующим транспортом:</div>
         
         <ul style="margin-top:9px;" class="transps">
            <li class="f-l">
                <div class="bus">Автобусом</div>
            </li>
            <li class="f-l">
                <div class="m-bus">Маршрутным&nbsp;такси</div>
            </li>
            <li></li>
         </ul>
    </div>
    <div class="f-r">
		<div class="abpoint-a">
			<input type="text" value="" />
		</div>
        <div class="abpoint-a-aft">Донбасс Арена, площадь Ленина,<br />аэропорт, ЖД вокзал</div>
		<div class="abpoint-b">
			<input type="text" readonly="readonly" value="площадь Ленина" />
		</div>
        <div style="margin-top:5px;padding-left:20px;">
    		<div class="travelling-mode driving selected"></div>
    		<div class="travelling-mode walking"></div>
    		<button class="c-button f-r">Проложить маршрут</button>
       </div>
	
    </div>
</div>
<script>
var Map = function(){
	var $this = this;
	/** Объект карты Google */
	var map;
	/** координаты Эквицентра */
	var eqLocation;
	/** маркер Эквицентра */
	var eqMarker;
	/** маркер, который будет отображен как результат поиска маршрута */
	var homeMarker;
	/** всплывающая подсказка к маркеру эквицентра */
	var eqInfo;
	/** тип маршрута, который будет прокладываться на карте */
	var travellingMode = google.maps.TravelMode.DRIVING;
	/** геокодирование результатов */
	var geocoder = new google.maps.Geocoder();
	
	var info;
	
	/** язык сайта */
	var lang;
	
	var googleErrors = [];
	
	/** отменяем вывод маркеров на карту при рендере */
	var directionsRenderOptions = {
		suppressMarkers: true
	};
	
	var directionsDisplay = new google.maps.DirectionsRenderer(directionsRenderOptions);
	var directionsService = new google.maps.DirectionsService();
	
	/** проложение маршрута */
	this.route = function(){
		var request = {
		    origin: $('.abpoint-a input').val(),
		    destination: eqLocation,
		    travelMode: travellingMode
		};
		directionsService.route(request, function(response, status) {
		   console.log(status)
			switch (status){
				case google.maps.DirectionsStatus.OK: 
					directionsDisplay.setDirections(response);
					var address = $('.abpoint-a > input').val();
                    
					geocoder.geocode({'address' : address},function(results,status){
						addHomeMarker(results[0].geometry.location,address);
					});
					break;
				case google.maps.DirectionsStatus.NOT_FOUND:
					alert(googleErrors[0]);
					break;
				case google.maps.DirectionsStatus.ZERO_RESULTS:
					alert(googleErrors[1]);
					break;
			}
		});
	}
	/** добавляем маркер начала поиска */
	function addHomeMarker(position, content){
		if (typeof(info) != 'undefined'){
			info.close();
		}
		info = new google.maps.InfoWindow();
		info.setContent(content);
		info.setPosition(position);
		
		if (typeof (homeMarker) != 'undefined'){
			homeMarker.setPosition(position);
		} else {
			homeMarker = new google.maps.Marker({
				position: position,
				map: map,
				icon: 'img/way/marker_start.png',
			});
			google.maps.event.addListener(homeMarker,'click',function(){
				info.open(map);
			});
		}
	}
	
	/** смена типа прокладывания маршрута */
	this.changeTravellingMode = function(){
		$(this).siblings().removeClass('selected').end().addClass('selected');
		if ($('.travelling-mode').index($(this)) == 0){
			travellingMode = google.maps.TravelMode.DRIVING;
		} else {
			travellingMode = google.maps.TravelMode.WALKING;
		}
		if ($.trim($('.abpoint-a>input').val()) != '') $this.route();
	}
	
	/** определение и установка языка */
	function determineLang(){
		var href = window.location.href;
		var regExp = /\/rus\//;
        lang = 'rus';
		/*if (href.search(regExp) != -1){
			lang = 'rus';
		} else {
			lang = 'eng';
		}*/
	}
	/** инициализируем языковые настройки */
	function initLang(){
		switch(lang){
			case 'rus':
				googleErrors[0] = "Адрес не найден. Пожалуйста, проверьте правильность введенного адреса!";
				googleErrors[1] = "Адрес не найден. Пожалуйста, проверьте правильность введенного адреса.";
				break;
			case 'eng':
				googleErrors[0] = "Address not found. Please check the entered address!";
				googleErrors[1] = "Sorry... No route could be found between the origin and destination!";
				break;
		}
	}
	
	/** инициализация */
	(function init(){
		determineLang();
		initLang();
		console.log('init')
		eqLocation = new google.maps.LatLng(47.94432,37.531142);
		var mapOptions = {
			zoom: 15,
			center: eqLocation,
			mapTypeId: google.maps.MapTypeId.ROADMAP,
			scrollwheel: false
		};
		map = new google.maps.Map(document.getElementById('map'),mapOptions);
		directionsDisplay.setMap(map);
		
		eqMarker = new google.maps.Marker({
			position: eqLocation,
			map: map,
			icon: 'img/way/marker.png',
			title: 'Equicenter'
		});
		
		eqInfo = new google.maps.InfoWindow({
			content: $("<div />").html($('.abpoint-a input').val()).css({paddingRight: '20px'}).get(0).outerHTML
		});
		
		google.maps.event.addListener(eqMarker,'click',function(){
			eqInfo.open(map,eqMarker);
		});
	})();
}
/** строим маршруты по нажатию ENTER'а */
var enter = function(e){
	if (e.keyCode == 13){
		$('.c-button').trigger('click');
	}
}

$(function(){
	var map = new Map();
	//$('.google-map-route input:first').focus();
	$('.c-button').on('click',function(){map.route});
	$('.travelling-mode').bind('click',map.changeTravellingMode);
	$('input').bind('keyup', enter);
});

</script>